/**
 * Class: payload schemas (`payload-schemas.json`), 4 cases per subscribed type.
 *
 * The class SC-014 and FR-033 need and nothing covers today. Generated by
 * running the real Zod schemas and recording the real parse result, never a
 * predicted one.
 *
 * The fourth case per type is the point of the class: an instance carrying a
 * field a newer client wrote, and the exact bytes that must come back out. A
 * client that deserialises into a struct and re-serialises fails it, which is
 * exactly what it is for (chapter 13 §13.2).
 *
 * Chapter: docs/protocol/13-payload-schemas.md.
 */
import type { ZodType } from 'zod'

import { SettingsSyncPayloadSchema } from '../../src/settings-sync'
import {
  CustomIconSyncPayloadSchema,
  FilterSyncPayloadSchema,
  FolderConfigSyncPayloadSchema,
  InboxSyncPayloadSchema,
  JournalSyncPayloadSchema,
  NoteSyncPayloadSchema,
  ProjectSyncPayloadSchema,
  PropertyDefinitionSyncPayloadSchema,
  ReminderSyncPayloadSchema,
  TagCategorySyncPayloadSchema,
  TagDefinitionSyncPayloadSchema,
  TaskActivitySyncPayloadSchema,
  TaskSyncPayloadSchema,
  TemplateSyncPayloadSchema
} from '../../src/sync-payloads'
import { meta } from './shared'

const CLOCK = { 'device-a': 1 }

interface TypeSpec {
  type: string
  schema: ZodType
  valid: Record<string, unknown>
  boundary: Record<string, unknown>
  /** The key a newer client wrote that this schema does not model. */
  unknownKey: string
  unknownValue: unknown
}

const SPECS: TypeSpec[] = [
  {
    type: 'note',
    schema: NoteSyncPayloadSchema,
    valid: {
      title: 'A note',
      content: '# A note\n\nBody.\n',
      tags: ['protocol'],
      pinnedTags: ['protocol'],
      emoji: '📓',
      properties: { area: 'Work' },
      aliases: ['note'],
      fileType: 'markdown',
      mimeType: 'text/markdown',
      attachmentId: null,
      attachmentReferences: ['att-1'],
      folderPath: 'Notes',
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z',
      modifiedAt: 1760000000000
    },
    boundary: { title: '', content: null, tags: [], clock: {} },
    unknownKey: 'coverImage',
    unknownValue: { url: 'memry://cover/1', offsetY: 0.25 }
  },
  {
    type: 'journal',
    schema: JournalSyncPayloadSchema,
    valid: {
      date: '2026-04-16',
      content: 'Today.',
      tags: ['daily'],
      properties: { mood: 'ok' },
      clock: CLOCK,
      createdAt: 1760000000000
    },
    boundary: { date: '2026-04-16', content: null, tags: [], properties: null, clock: {} },
    unknownKey: 'weather',
    unknownValue: 'clear'
  },
  {
    type: 'folder_config',
    schema: FolderConfigSyncPayloadSchema,
    valid: {
      icon: 'folder',
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z',
      modifiedAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: { icon: null, clock: {} },
    unknownKey: 'sortMode',
    unknownValue: 'manual'
  },
  {
    type: 'custom_icon',
    schema: CustomIconSyncPayloadSchema,
    valid: {
      name: 'rocket',
      ext: 'png',
      data: 'iVBORw0KGgo=',
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z',
      updatedAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: { name: '', ext: '', data: '', clock: {} },
    unknownKey: 'sourceUrl',
    unknownValue: 'https://example.invalid/rocket.png'
  },
  {
    type: 'tag_definition',
    schema: TagDefinitionSyncPayloadSchema,
    valid: {
      name: 'protocol',
      color: '#4f46e5',
      colorAuthored: true,
      icon: 'tag',
      categoryId: 'cat-1',
      sortOrder: 3,
      views: [],
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: { name: 'protocol', color: '#4f46e5', views: null, clock: {} },
    unknownKey: 'pinned',
    unknownValue: true
  },
  {
    type: 'tag_category',
    schema: TagCategorySyncPayloadSchema,
    valid: {
      name: 'Topics',
      sortOrder: 1,
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z',
      updatedAt: '2026-04-16T00:00:00.000Z',
      deletedAt: null
    },
    boundary: { name: '', sortOrder: 0, clock: {} },
    unknownKey: 'icon',
    unknownValue: 'hash'
  },
  {
    type: 'property_definition',
    schema: PropertyDefinitionSyncPayloadSchema,
    valid: {
      name: 'area',
      type: 'select',
      options: '[{"value":"Work","color":"indigo"}]',
      defaultValue: 'Work',
      color: 'indigo',
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: { name: 'area', type: 'text', options: null, clock: {} },
    unknownKey: 'description',
    unknownValue: 'Which area of life this belongs to'
  },
  {
    type: 'template',
    schema: TemplateSyncPayloadSchema,
    valid: {
      name: 'Daily',
      description: 'A daily note',
      icon: 'sun',
      tags: ['daily'],
      properties: [],
      content: '# {{date}}\n',
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z',
      modifiedAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: { name: '', tags: [], properties: [], content: '', clock: {} },
    unknownKey: 'folderPath',
    unknownValue: 'Templates/Daily'
  },
  {
    type: 'task',
    schema: TaskSyncPayloadSchema,
    valid: {
      title: 'Ship the spec',
      description: 'All fifteen chapters.',
      projectId: 'proj-1',
      statusId: 'status-1',
      parentId: null,
      priority: 2,
      position: 1024,
      dueDate: '2026-04-20',
      dueTime: '09:00',
      startDate: '2026-04-16',
      repeatConfig: { every: 'week', on: ['mon'] },
      repeatFrom: 'dueDate',
      sourceNoteId: 'abc123def456',
      completedAt: null,
      archivedAt: null,
      tags: ['protocol'],
      linkedNoteIds: ['abc123def456'],
      linkedCanvasIds: [],
      clock: CLOCK,
      fieldClocks: { title: CLOCK },
      createdAt: '2026-04-16T00:00:00.000Z',
      modifiedAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: {
      title: '',
      description: null,
      tags: [],
      linkedNoteIds: [],
      clock: {},
      fieldClocks: {}
    },
    unknownKey: 'estimateMinutes',
    unknownValue: 45
  },
  {
    type: 'project',
    schema: ProjectSyncPayloadSchema,
    valid: {
      name: 'Native iOS',
      description: 'The Rust core and its shell.',
      color: '#0ea5e9',
      icon: 'rocket',
      position: 1,
      isInbox: false,
      archivedAt: null,
      homeNoteId: 'abc123def456',
      statuses: [{ id: 'status-1', name: 'Todo', color: '#888', position: 0, isDefault: true }],
      links: [],
      clock: CLOCK,
      fieldClocks: { name: CLOCK },
      createdAt: '2026-04-16T00:00:00.000Z',
      modifiedAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: { name: '', statuses: [], links: [], clock: {}, fieldClocks: {} },
    unknownKey: 'defaultViewId',
    unknownValue: 'view-1'
  },
  {
    type: 'task_activity',
    schema: TaskActivitySyncPayloadSchema,
    valid: {
      taskId: 'task-1',
      action: 'superseded',
      field: 'title',
      oldValue: '"old"',
      newValue: '"new"',
      actor: 'user',
      deviceId: 'device-a',
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: {
      taskId: 'task-1',
      action: 'created',
      field: null,
      oldValue: null,
      newValue: null,
      clock: {}
    },
    unknownKey: 'clientPlatform',
    unknownValue: 'ios'
  },
  {
    type: 'reminder',
    schema: ReminderSyncPayloadSchema,
    valid: {
      targetType: 'note',
      targetId: 'abc123def456',
      remindAt: '2026-04-20T09:00:00.000Z',
      anchorId: 'anchor-1',
      highlightText: 'this line',
      highlightStart: 10,
      highlightEnd: 19,
      title: 'Reread',
      note: null,
      status: 'pending',
      dismissedAt: null,
      snoozedUntil: null,
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z',
      modifiedAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: {
      targetType: 'note',
      targetId: 'abc123def456',
      remindAt: '2026-04-20T09:00:00.000Z',
      status: 'pending',
      clock: {}
    },
    // The field the schema deliberately omits, so a newer client sending it is
    // exactly the SC-014 case rather than a hypothetical one.
    unknownKey: 'triggeredAt',
    unknownValue: '2026-04-20T09:00:01.000Z'
  },
  {
    type: 'settings',
    schema: SettingsSyncPayloadSchema,
    valid: { settings: { general: { theme: 'dark' } }, fieldClocks: { 'general.theme': CLOCK } },
    boundary: { settings: {}, fieldClocks: {} },
    unknownKey: 'settings.experimental',
    unknownValue: null
  },
  {
    // Saved task filters, subscribed since spec 004 TP022. `config` is
    // `z.unknown()`, so a key inside it is never stripped; the unknown case is
    // a top-level key desktop's own push carries (it serialises the whole row).
    type: 'filter',
    schema: FilterSyncPayloadSchema,
    valid: {
      name: 'Due this week',
      config: {
        filters: {
          search: '',
          projectIds: ['proj-1'],
          priorities: ['high'],
          tags: [],
          dueDate: { type: 'this-week', customStart: null, customEnd: null },
          statusIds: [],
          completion: 'active',
          repeatType: 'all',
          hasTime: 'all'
        },
        sort: { field: 'dueDate', direction: 'asc' },
        starred: true
      },
      position: 2,
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: { name: '', config: {}, position: 0, clock: {} },
    unknownKey: 'syncedAt',
    unknownValue: '2026-04-16T00:00:01.000Z'
  },
  {
    // Inbox captures, subscribed since spec 006 IB012. Desktop pushes its whole
    // `inbox_items` row, so its local columns (`transcription`, `viewedAt`,
    // ...) are the unknown keys a real payload carries; `metadata` is
    // `z.unknown()` and never stripped inside.
    type: 'inbox',
    schema: InboxSyncPayloadSchema,
    valid: {
      title: 'How Linear builds product',
      content: 'Small teams, short cycles.',
      type: 'link',
      metadata: { url: 'https://example.com/agent/1', fetchStatus: 'complete', siteName: 'Linear' },
      filedAt: null,
      filedTo: null,
      filedAction: null,
      snoozedUntil: '2026-04-17T09:00:00.000Z',
      snoozeReason: null,
      archivedAt: null,
      sourceUrl: 'https://example.com/agent/1',
      sourceTitle: null,
      captureSource: 'inline',
      clock: CLOCK,
      createdAt: '2026-04-16T00:00:00.000Z',
      modifiedAt: '2026-04-16T00:00:00.000Z'
    },
    boundary: { title: '', content: null, metadata: null, clock: {} },
    unknownKey: 'transcription',
    unknownValue: 'Pick up the cable before Friday.'
  }
]

/** The settings unknown case is a GROUP, not a top-level key. */
function unknownInstance(spec: TypeSpec): Record<string, unknown> {
  if (spec.type === 'settings') {
    return {
      settings: { general: { theme: 'dark' }, experimental: { agentSidebar: true } },
      fieldClocks: { 'general.theme': CLOCK, 'experimental.agentSidebar': CLOCK }
    }
  }
  return { ...spec.valid, [spec.unknownKey]: spec.unknownValue }
}

export function buildPayloadSchemas(): Record<string, unknown> {
  const groups = SPECS.map((spec) => {
    const unknown = unknownInstance(spec)
    const unknownJson = JSON.stringify(unknown)
    const parsedUnknown = spec.schema.parse(unknown) as Record<string, unknown>
    return {
      type: spec.type,
      cases: [
        {
          name: `${spec.type}: valid, every modelled field populated`,
          payload: spec.valid,
          expectedParsed: spec.schema.parse(spec.valid),
          pins: "the projector's field list against the payload's"
        },
        {
          name: `${spec.type}: boundary — empty strings, empty arrays, optionals absent`,
          payload: spec.boundary,
          expectedParsed: spec.schema.parse(spec.boundary),
          pins: 'absent and empty stay distinct across the round trip'
        },
        {
          name: `${spec.type}: an unknown field a newer client wrote`,
          payload: unknown,
          expectedParsed: parsedUnknown,
          strippedByParse:
            spec.type === 'settings'
              ? ['settings.experimental']
              : Object.keys(unknown).filter((k) => !(k in parsedUnknown)),
          pins: 'THE SC-014 CASE: Zod strips the key from the PARSED object, and the stored payload string must not change'
        },
        {
          name: `${spec.type}: verbatim round trip of the unknown-field instance`,
          storedPayloadJson: unknownJson,
          expectedPushedPayloadJson: unknownJson,
          pins: 'the exact bytes that must come back out. An implementation that deserialises into a struct and re-serialises fails here'
        }
      ]
    }
  })

  return {
    meta: meta({
      class: 'payload-schemas',
      chapter: 'docs/protocol/13-payload-schemas.md',
      schemas: 'packages/contracts/src/sync-payloads.ts, packages/contracts/src/settings-sync.ts',
      subscribedTypes: SPECS.map((s) => s.type),
      obligation:
        'a payload schema is a READER over a preserved string, never the storage shape (FR-033)',
      caseCount: groups.reduce((n, g) => n + g.cases.length, 0)
    }),
    groups
  }
}
