import { readFileSync } from 'node:fs'
import { describe, it, expect, beforeEach, vi } from 'vitest'
import { eq } from 'drizzle-orm'
import { inboxItems } from '@memry/db-schema/schema/inbox'
import { InboxSyncPayloadSchema } from '@memry/contracts/sync-payloads'
import { createTestDataDb, type TestDataDb } from '../../../test/helpers/test-data-db'

vi.mock('../../lib/logger', () => ({
  createLogger: () => ({
    info: vi.fn(),
    warn: vi.fn(),
    error: vi.fn(),
    debug: vi.fn()
  })
}))

import { inboxHandler } from './inbox-handler'

/**
 * Spec 006 IB028: the payloads the iOS core pushes over one capture's
 * lifecycle (generated by `crates/memry-core/tests/domain_inbox_write.rs`)
 * parse with the current schema and apply through this handler, including the
 * explicit-null clears that unsnooze, unarchive and unfile send.
 */
let db: TestDataDb
const emit = vi.fn()
const ctx = () => ({ db, emit })
const rowOf = (id: string) => db.select().from(inboxItems).where(eq(inboxItems.id, id)).get()

type Step = { step: string; payload: Record<string, unknown> }
const fixture = JSON.parse(
  readFileSync(
    new URL(
      '../../../../../../packages/contracts/test-vectors/inbox-ios-payloads.json',
      import.meta.url
    ),
    'utf8'
  )
) as { itemId: string; steps: Step[] }
const steps = fixture.steps
const itemId = fixture.itemId

function apply(step: Step): string {
  const data = InboxSyncPayloadSchema.parse(step.payload)
  return inboxHandler.applyUpsert(ctx(), itemId, data, (data.clock ?? {}) as Record<string, number>)
}

beforeEach(() => {
  db = createTestDataDb()
  emit.mockClear()
})

describe('inboxHandler with iOS payloads', () => {
  it('parses every payload the phone writes', () => {
    for (const step of steps) {
      expect(InboxSyncPayloadSchema.safeParse(step.payload).success, step.step).toBe(true)
    }
  })

  it('applies the lifecycle and ends where the phone did', () => {
    const byName = new Map(steps.map((s) => [s.step, s]))
    const step = (name: string): Step => {
      const found = byName.get(name)
      if (!found) throw new Error(`missing step ${name}`)
      return found
    }

    expect(apply(step('capture'))).toBe('applied')
    expect(rowOf(itemId)).toMatchObject({
      type: 'note',
      title: '[agent] from the phone',
      captureSource: 'inline',
      snoozedUntil: null,
      archivedAt: null
    })

    apply(step('snooze'))
    expect(rowOf(itemId)?.snoozedUntil).toBeTruthy()
    expect(rowOf(itemId)?.snoozeReason).toBe('later')

    apply(step('unsnooze'))
    expect(rowOf(itemId)).toMatchObject({ snoozedUntil: null, snoozeReason: null })

    apply(step('archive'))
    expect(rowOf(itemId)?.archivedAt).toBeTruthy()
    apply(step('unarchive'))
    expect(rowOf(itemId)?.archivedAt).toBeNull()

    apply(step('file'))
    expect(rowOf(itemId)).toMatchObject({
      filedTo: 'Agent Test/[agent] from the phone.md',
      filedAction: 'folder'
    })
    apply(step('unfile'))
    expect(rowOf(itemId)).toMatchObject({ filedAt: null, filedTo: null, filedAction: null })
  })

  it('does not let a replayed older phone payload undo a newer one', () => {
    apply(steps[steps.length - 1])
    expect(apply(steps[1])).toBe('skipped')
    expect(rowOf(itemId)?.snoozedUntil).toBeNull()
  })
})
