import type { ReactDoctorConfig } from "react-doctor/api";

export default {
  ignore: {
    files: [
      "**/tests/**",
      "**/*.test.ts",
      "**/*.test.tsx",
      "**/*.spec.ts",
      "**/*.spec.tsx",
      "**/fixtures/**",
      "**/generated/**",
      "**/out/**",
      "**/dist/**",
      "**/.wrangler/**"
    ],
    rules: [
      "knip/duplicates",
      "knip/exports",
      "knip/files",
      "knip/types",
      "react-doctor/advanced-event-handler-refs",
      "react-doctor/async-await-in-loop",
      "react-doctor/async-defer-await",
      "react-doctor/async-parallel",
      "react-doctor/client-passive-event-listeners",
      "react-doctor/design-no-default-tailwind-palette",
      "react-doctor/design-no-em-dash-in-jsx-text",
      "react-doctor/design-no-redundant-padding-axes",
      "react-doctor/design-no-redundant-size-axes",
      "react-doctor/design-no-space-on-flex-children",
      "react-doctor/design-no-three-period-ellipsis",
      "react-doctor/js-batch-dom-css",
      "react-doctor/js-cache-property-access",
      "react-doctor/js-cache-storage",
      "react-doctor/js-combine-iterations",
      "react-doctor/js-flatmap-filter",
      "react-doctor/js-hoist-intl",
      "react-doctor/js-index-maps",
      "react-doctor/js-length-check-first",
      "react-doctor/js-min-max-loop",
      "react-doctor/js-set-map-lookups",
      "react-doctor/js-tosorted-immutable",
      "react-doctor/no-barrel-import",
      "react-doctor/no-cascading-set-state",
      "react-doctor/no-derived-useState",
      "react-doctor/no-dynamic-import-path",
      "react-doctor/no-effect-event-handler",
      "react-doctor/no-fetch-in-effect",
      "react-doctor/no-flush-sync",
      "react-doctor/no-generic-handler-names",
      "react-doctor/no-giant-component",
      "react-doctor/no-inline-bounce-easing",
      "react-doctor/no-inline-exhaustive-style",
      "react-doctor/no-many-boolean-props",
      "react-doctor/no-pure-black-background",
      "react-doctor/no-react19-deprecated-apis",
      "react-doctor/no-render-in-render",
      "react-doctor/no-scale-from-zero",
      "react-doctor/no-side-tab-border",
      "react-doctor/no-tiny-text",
      "react-doctor/no-z-index-9999",
      "react-doctor/prefer-use-effect-event",
      "react-doctor/prefer-useReducer",
      "react-doctor/query-mutation-missing-invalidation",
      "react-doctor/rendering-conditional-render",
      "react-doctor/rendering-hydration-mismatch-time",
      "react-doctor/rendering-svg-precision",
      "react-doctor/rendering-usetransition-loading",
      "react-doctor/rerender-functional-setstate",
      "react-doctor/rerender-lazy-state-init",
      "react-doctor/rerender-memo-before-early-return",
      "react-doctor/rerender-memo-with-default-value",
      "react-doctor/rerender-state-only-in-handlers",
      "react-doctor/server-dedup-props",
      "react-doctor/server-sequential-independent-await",
      "react-doctor/use-lazy-motion",
      "react/no-danger",
      "jsx-a11y/click-events-have-key-events",
      "jsx-a11y/heading-has-content",
      "jsx-a11y/iframe-has-title",
      "jsx-a11y/label-has-associated-control",
      "jsx-a11y/no-autofocus",
      "jsx-a11y/no-static-element-interactions"
    ]
  },
  lint: true,
  deadCode: true,
  failOn: "error"
} satisfies ReactDoctorConfig;
