#!/usr/bin/env node

import fs from 'node:fs'
import path from 'node:path'
import { rpcDomains } from '../../../packages/rpc/src/index.ts'

const REPO_ROOT = path.resolve(import.meta.dirname, '..')
const OUTPUT_PATH = path.join(REPO_ROOT, 'src/preload/generated-rpc.ts')
const CHECK_MODE = process.argv.includes('--check')

function renderMethod(domainName: string, methodName: string, spec: (typeof rpcDomains)[number]['methods'][string]) {
  const params = spec.params.join(', ')
  const invokeArgs = spec.invokeArgs.join(', ')
  const argsSuffix = invokeArgs.length > 0 ? `, ${invokeArgs}` : ''
  const runner = spec.implementation
    ? `(${spec.implementation})`
    : spec.mode === 'sync'
      ? `(() => invokeSync(${JSON.stringify(spec.channel)}))`
      : `((${params}) => invoke(${JSON.stringify(spec.channel)}${argsSuffix}))`

  return `      ${methodName}: ${runner} as GeneratedRpcApi[${JSON.stringify(domainName)}][${JSON.stringify(methodName)}],`
}

function renderEvent(eventName: string, spec: (typeof rpcDomains)[number]['events'][string]) {
  return `    ${eventName}: ((callback) => subscribe(${JSON.stringify(spec.channel)}, callback)) as GeneratedRpcApi[${JSON.stringify(eventName)}],`
}

function generateOutput() {
  const lines = [
    '// Auto-generated by scripts/generate-rpc-bindings.ts. Do not edit manually.',
    '',
    "export type { GeneratedRpcApi } from '@memry/rpc'",
    "import type { GeneratedRpcApi } from '@memry/rpc'",
    "import type { MainIpcInvokeArgs, MainIpcInvokeChannel, MainIpcInvokeResult } from '../main/ipc/generated-ipc-invoke-map'",
    '',
    'export interface GeneratedRpcDeps {',
    '  invoke<C extends MainIpcInvokeChannel>(',
    '    channel: C,',
    '    ...args: MainIpcInvokeArgs<C>',
    '  ): Promise<MainIpcInvokeResult<C>>',
    '  invokeSync(channel: string): unknown',
    '  subscribe<T>(channel: string, callback: (payload: T) => void): () => void',
    '}',
    '',
    'export function createGeneratedRpcApi({',
    '  invoke,',
    '  invokeSync,',
    '  subscribe',
    '}: GeneratedRpcDeps): GeneratedRpcApi {',
    '  return {'
  ]

  for (const domain of rpcDomains) {
    lines.push(`    ${domain.name}: {`)
    for (const [methodName, spec] of Object.entries(domain.methods)) {
      lines.push(renderMethod(domain.name, methodName, spec))
    }
    lines.push('    },')
  }

  for (const domain of rpcDomains) {
    for (const [eventName, spec] of Object.entries(domain.events)) {
      lines.push(renderEvent(eventName, spec))
    }
  }

  lines.push('  }')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

function main() {
  const output = generateOutput()
  const current = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, 'utf8') : ''

  if (CHECK_MODE) {
    if (current !== output) {
      console.error(
        'Generated RPC bindings are out of date. Run: node --experimental-strip-types --experimental-transform-types scripts/generate-rpc-bindings.ts'
      )
      process.exit(1)
    }

    console.log('Generated RPC bindings are up to date')
    return
  }

  fs.writeFileSync(OUTPUT_PATH, output, 'utf8')
  console.log(`Wrote ${path.relative(REPO_ROOT, OUTPUT_PATH)}`)
}

main()
