#!/usr/bin/env node

import { randomBytes } from 'node:crypto'
import fs from 'node:fs'
import path from 'node:path'
import { rpcDomains } from '../../../packages/rpc/src/index.ts'

const REPO_ROOT = path.resolve(import.meta.dirname, '..')
const OUTPUT_PATH = path.join(REPO_ROOT, 'src/preload/generated-rpc.ts')
const CHECK_MODE = process.argv.includes('--check')

function normalizeGeneratedText(text: string) {
  return text.replace(/\r\n?/g, '\n')
}

function renderPropertyKey(name: string) {
  return JSON.stringify(name)
}

function collectEventChannels() {
  const eventChannels: Record<string, string> = {}

  for (const domain of rpcDomains) {
    for (const [eventName, spec] of Object.entries(domain.events)) {
      eventChannels[eventName] = spec.channel
    }
  }

  return eventChannels
}

function writeFileAtomically(filePath: string, content: string) {
  const dir = path.dirname(filePath)
  const tempPath = path.join(
    dir,
    `.${path.basename(filePath)}.${randomBytes(6).toString('hex')}.tmp`
  )
  const fd = fs.openSync(tempPath, 'wx', 0o600)

  try {
    fs.writeFileSync(fd, content, 'utf8')
    fs.closeSync(fd)
    fs.renameSync(tempPath, filePath)
  } catch (error) {
    try {
      fs.closeSync(fd)
    } catch {
      // already closed
    }
    fs.rmSync(tempPath, { force: true })
    throw error
  }
}

function readExistingFile(filePath: string): string {
  try {
    return fs.readFileSync(filePath, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return ''
    }

    throw error
  }
}

function renderMethod(
  domainName: string,
  methodName: string,
  spec: (typeof rpcDomains)[number]['methods'][string]
) {
  const params = spec.params.join(', ')
  const invokeArgs = spec.invokeArgs.join(', ')
  const argsSuffix = invokeArgs.length > 0 ? `, ${invokeArgs}` : ''
  const runner = spec.implementation
    ? `(${spec.implementation})`
    : spec.mode === 'sync'
      ? `(() => invokeSync(${JSON.stringify(spec.channel)}))`
      : `((${params}) => invoke(${JSON.stringify(spec.channel)}${argsSuffix}))`

  return `      ${renderPropertyKey(methodName)}: ${runner} as GeneratedRpcApi[${JSON.stringify(domainName)}][${JSON.stringify(methodName)}],`
}

function generateOutput() {
  const lines = [
    '// Auto-generated by scripts/generate-rpc-bindings.ts. Do not edit manually.',
    '',
    "export type { GeneratedRpcApi } from '@memry/rpc'",
    "import type { GeneratedRpcApi } from '@memry/rpc'",
    "import type { MainIpcInvokeArgs, MainIpcInvokeChannel, MainIpcInvokeResult } from '../main/ipc/generated-ipc-invoke-map'",
    '',
    `const eventChannels = ${JSON.stringify(collectEventChannels(), null, 2)} as const`,
    '',
    'export interface GeneratedRpcDeps {',
    '  invoke<C extends MainIpcInvokeChannel>(',
    '    this: void,',
    '    channel: C,',
    '    ...args: MainIpcInvokeArgs<C>',
    '  ): Promise<MainIpcInvokeResult<C>>',
    '  invokeSync(this: void, channel: string): unknown',
    '  subscribe<T>(this: void, channel: string, callback: (payload: T) => void): () => void',
    '}',
    '',
    'export function createGeneratedRpcApi({',
    '  invoke,',
    '  invokeSync,',
    '  subscribe',
    '}: GeneratedRpcDeps): GeneratedRpcApi {',
    '  const api = {'
  ]

  for (const domain of rpcDomains) {
    lines.push(`    ${renderPropertyKey(domain.name)}: {`)
    for (const [methodName, spec] of Object.entries(domain.methods)) {
      lines.push(renderMethod(domain.name, methodName, spec))
    }
    lines.push('    },')
  }

  lines.push('  }')
  lines.push('')
  lines.push('  for (const [eventName, channel] of Object.entries(eventChannels)) {')
  lines.push('    ;(api as Record<string, unknown>)[eventName] = ((')
  lines.push('      callback: (payload: unknown) => void')
  lines.push('    ) => subscribe(channel, callback))')
  lines.push('  }')
  lines.push('')
  lines.push('  return api as GeneratedRpcApi')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

function main() {
  const output = generateOutput()
  const current = readExistingFile(OUTPUT_PATH)

  if (CHECK_MODE) {
    if (normalizeGeneratedText(current) !== normalizeGeneratedText(output)) {
      console.error(
        'Generated RPC bindings are out of date. Run: node --experimental-strip-types --experimental-transform-types scripts/generate-rpc-bindings.ts'
      )
      process.exit(1)
    }

    console.log('Generated RPC bindings are up to date')
    return
  }

  writeFileAtomically(OUTPUT_PATH, output)
  console.log(`Wrote ${path.relative(REPO_ROOT, OUTPUT_PATH)}`)
}

main()
