import { z } from 'zod'

export const AgentMcpChannels = {
  invoke: {
    GET_STATUS: 'agent_mcp:get_status',
    ['ROTATE_TOKEN']: 'agent_mcp:rotate_token'
  }
} as const

export const AgentMcpDesktopApiChannel = 'agent_mcp:desktop_api'

export const AgentMcpDesktopReadOperations = [
  'notes.get',
  'notes.getByPath',
  'notes.getFile',
  'notes.resolveByTitle',
  'notes.previewByTitle',
  'notes.list',
  'notes.getTags',
  'notes.getLinks',
  'notes.getFolders',
  'notes.exists',
  'notes.getPropertyDefinitions',
  'notes.listAttachments',
  'notes.getFolderConfig',
  'notes.getFolderTemplate',
  'notes.getVersions',
  'notes.getVersion',
  'notes.getPositions',
  'notes.getAllPositions',
  'notes.getLocalOnlyCount',
  'notes.getCalendarPropertyNames',
  'tasks.get',
  'tasks.list',
  'tasks.getSubtasks',
  'tasks.getProject',
  'tasks.listProjects',
  'tasks.listStatuses',
  'tasks.getTags',
  'tasks.getStats',
  'tasks.getToday',
  'tasks.getUpcoming',
  'tasks.getOverdue',
  'tasks.getLinkedTasks',
  'tasks.listProjectLinks',
  'tasks.listProjectContents',
  'tasks.listForItem',
  'inbox.get',
  'inbox.list',
  'inbox.previewLink',
  'inbox.getSuggestions',
  'inbox.getTags',
  'inbox.getSnoozed',
  'inbox.getStats',
  'inbox.getJobs',
  'inbox.getPatterns',
  'inbox.getStaleThreshold',
  'inbox.listArchived',
  'inbox.getFilingHistory',
  'journal.getEntry',
  'journal.getHeatmap',
  'journal.getMonthEntries',
  'journal.getYearStats',
  'journal.getDayContext',
  'journal.getAllTags',
  'journal.getStreak',
  'properties.get',
  'templates.list',
  'templates.get',
  'savedFilters.list',
  'bookmarks.get',
  'bookmarks.list',
  'bookmarks.isBookmarked',
  'bookmarks.listByType',
  'bookmarks.getByItem',
  'tags.getNotesByTag',
  'tags.getAllWithCounts',
  'folderView.getConfig',
  'folderView.getViews',
  'folderView.listWithProperties',
  'folderView.getAvailableProperties',
  'folderView.getFolderSuggestions',
  'folderView.folderExists',
  'reminders.get',
  'reminders.list',
  'reminders.getUpcoming',
  'reminders.getDue',
  'reminders.getForTarget',
  'reminders.countPending',
  // Google Workspace Limited Use: agent backends may only see native memrynote
  // calendar data. Google-integration operations (sources, provider status,
  // Google calendar lists, Google settings) must stay out of both allowlists.
  'calendar.getEvent',
  'calendar.listEvents',
  'calendar.getRange',
  'settings.get',
  'settings.getJournalSettings',
  'settings.getAISettings',
  'settings.getVoiceTranscriptionSettings',
  'settings.getVoiceModelStatus',
  'settings.getVoiceRecordingReadiness',
  'settings.getVoiceTranscriptionOpenAIKeyStatus',
  'settings.getAIModelStatus',
  'settings.getTabSettings',
  'settings.getNoteEditorSettings',
  'settings.getGeneralSettings',
  'settings.getEditorSettings',
  'settings.getTaskSettings',
  'settings.getKeyboardSettings',
  'settings.getSyncSettings',
  'settings.getBackupSettings',
  'settings.getGraphSettings',
  'settings.getCalendarSettings',
  'settings.getFeaturesSettings',
  'settings.getInboxSettings',
  'search.query',
  'search.quick',
  'search.getStats',
  'search.getReasons',
  'search.getAllTags',
  'graph.getData',
  'graph.getLocal',
  'homePages.list',
  'homePages.get',
  'vault.getAll',
  'vault.getStatus',
  'vault.getConfig',
  'vault.listAccount'
] as const

export const AgentMcpDesktopWriteOperations = [
  'notes.create',
  'notes.update',
  'notes.rename',
  'notes.move',
  'notes.delete',
  'notes.createFolder',
  'notes.renameFolder',
  'notes.deleteFolder',
  'notes.createPropertyDefinition',
  'notes.updatePropertyDefinition',
  'notes.ensurePropertyDefinition',
  'notes.addPropertyOption',
  'notes.addStatusOption',
  'notes.removePropertyOption',
  'notes.renamePropertyOption',
  'notes.updateOptionColor',
  'notes.deletePropertyDefinition',
  'notes.uploadAttachment',
  'notes.deleteAttachment',
  'notes.setFolderConfig',
  'notes.restoreVersion',
  'notes.deleteVersion',
  'notes.reorder',
  'notes.importFiles',
  'notes.setLocalOnly',
  'notes.setCalendarPropertyVisibility',
  'notes.applyTemplate',
  'notes.exportPdf',
  'notes.exportHtml',
  'tasks.create',
  'tasks.update',
  'tasks.delete',
  'tasks.complete',
  'tasks.uncomplete',
  'tasks.archive',
  'tasks.unarchive',
  'tasks.move',
  'tasks.reorder',
  'tasks.duplicate',
  'tasks.convertToSubtask',
  'tasks.convertToTask',
  'tasks.createProject',
  'tasks.updateProject',
  'tasks.deleteProject',
  'tasks.archiveProject',
  'tasks.reorderProjects',
  'tasks.linkProjectItem',
  'tasks.unlinkProjectItem',
  'tasks.setProjectLinkPinned',
  'tasks.setProjectHomeNote',
  // These two reach the network and the filesystem, but on caller-supplied
  // input only — the same footing as the allowlisted `inbox.captureLink` and
  // `notes.importFiles`. What stays out is opening native UI or handing an
  // item to the OS (`notes.showImportDialog`, `notes.openExternal`,
  // `notes.revealInFinder`).
  'tasks.captureUrlToProject',
  'tasks.importFilesToProject',
  'tasks.createStatus',
  'tasks.updateStatus',
  'tasks.deleteStatus',
  'tasks.reorderStatuses',
  'tasks.bulkComplete',
  'tasks.bulkDelete',
  'tasks.bulkMove',
  'tasks.bulkArchive',
  'inbox.captureText',
  'inbox.captureLink',
  'inbox.captureImage',
  'inbox.captureVoice',
  'inbox.captureClip',
  'inbox.capturePdf',
  'inbox.update',
  'inbox.archive',
  'inbox.file',
  'inbox.trackSuggestion',
  'inbox.convertToNote',
  'inbox.convertToTask',
  'inbox.convertToEvent',
  'inbox.convertToReminder',
  'inbox.linkToNote',
  'inbox.addTag',
  'inbox.removeTag',
  'inbox.snooze',
  'inbox.unsnooze',
  'inbox.markViewed',
  'inbox.bulkFile',
  'inbox.bulkArchive',
  'inbox.bulkTag',
  'inbox.bulkSnooze',
  'inbox.fileAllStale',
  'inbox.retryTranscription',
  'inbox.retryMetadata',
  'inbox.setStaleThreshold',
  'inbox.unarchive',
  'inbox.deletePermanent',
  'inbox.undoFile',
  'inbox.undoArchive',
  'journal.createEntry',
  'journal.updateEntry',
  'journal.deleteEntry',
  'properties.set',
  'properties.rename',
  'templates.create',
  'templates.update',
  'templates.delete',
  'templates.duplicate',
  'savedFilters.create',
  'savedFilters.update',
  'savedFilters.delete',
  'savedFilters.reorder',
  'bookmarks.create',
  'bookmarks.delete',
  'bookmarks.toggle',
  'bookmarks.reorder',
  'bookmarks.bulkDelete',
  'bookmarks.bulkCreate',
  'tags.pinNoteToTag',
  'tags.unpinNoteFromTag',
  'tags.renameTag',
  'tags.updateTagColor',
  'tags.deleteTag',
  'tags.removeTagFromNote',
  'tags.mergeTag',
  'tags.updateTagIcon',
  'folderView.setConfig',
  'folderView.setView',
  'folderView.deleteView',
  'reminders.create',
  'reminders.update',
  'reminders.delete',
  'reminders.dismiss',
  'reminders.snooze',
  'reminders.bulkDismiss',
  'calendar.createEvent',
  'calendar.updateEvent',
  'calendar.deleteEvent',
  'settings.set',
  'settings.setJournalSettings',
  'settings.setAISettings',
  'settings.setVoiceTranscriptionSettings',
  'settings.setTabSettings',
  'settings.setNoteEditorSettings',
  'settings.setGeneralSettings',
  'settings.setEditorSettings',
  'settings.setTaskSettings',
  'settings.setKeyboardSettings',
  'settings.resetKeyboardSettings',
  'settings.setSyncSettings',
  'settings.setBackupSettings',
  'settings.setGraphSettings',
  'settings.setCalendarSettings',
  'settings.setFeaturesSettings',
  'settings.setInboxSettings',
  'search.rebuildIndex',
  'search.addReason',
  'search.clearReasons',
  'homePages.create',
  'homePages.update',
  'homePages.delete',
  'homePages.reorder',
  'vault.switch',
  'vault.reindex',
  'vault.updateConfig',
  'vault.downloadRemote'
] as const

export const AgentMcpDesktopOperations = [
  ...AgentMcpDesktopReadOperations,
  ...AgentMcpDesktopWriteOperations
] as const

export type AgentMcpDesktopReadOperation = (typeof AgentMcpDesktopReadOperations)[number]
export type AgentMcpDesktopWriteOperation = (typeof AgentMcpDesktopWriteOperations)[number]
export type AgentMcpDesktopOperation = (typeof AgentMcpDesktopOperations)[number]

export function isAgentMcpDesktopOperation(value: string): value is AgentMcpDesktopOperation {
  return (AgentMcpDesktopOperations as readonly string[]).includes(value)
}

export const AgentMcpDesktopApiRequestSchema = z.object({
  operation: z.enum(AgentMcpDesktopOperations),
  args: z.array(z.unknown()).default([])
})

export type AgentMcpDesktopApiRequest = z.infer<typeof AgentMcpDesktopApiRequestSchema>

export type AgentMcpDesktopApiResponse =
  | { ok: true; data: unknown }
  | { ok: false; error: { code: string; message: string } }

export const AgentMcpStatusSchema = z.object({
  url: z.string().nullable(),
  ['token']: z.string().nullable(),
  toolCount: z.number().int().nonnegative()
})

export type AgentMcpStatus = z.infer<typeof AgentMcpStatusSchema>
