/**
 * One sentence per desktop API operation an agent can call through
 * `vault_desktop_read` / `vault_desktop_write`: what it does or returns.
 * `vault_desktop_describe` replies with it and the agent API reference prints
 * it next to the argument schema, so a new operation needs one here before it
 * type-checks.
 */
import type { AgentMcpDesktopOperation } from './agent-mcp-channels'

export const AGENT_DESKTOP_OPERATION_SUMMARIES = {
  'notes.get': 'Read a note by id: its markdown content, frontmatter, tags and metadata.',
  'notes.getByPath': 'Read a note by its vault-relative file path.',
  'notes.getFile': 'Read a filed file (PDF, image, audio, video) by id: its path and metadata.',
  'notes.resolveByTitle': 'Find the note with this exact title; null when none matches.',
  'notes.resolveWikiTarget':
    'Resolve the target of a [[wiki link]] the way the editor does, including #heading targets.',
  'notes.previewByTitle': 'A short preview (title, snippet, metadata) of the note with this title.',
  'notes.list': 'List notes, filtered by folder or tags, sorted and paged.',
  'notes.getTags': 'Every tag used on notes, with how many notes carry it.',
  'notes.getLinks': 'The outgoing links and backlinks of a note.',
  'notes.getFolders': 'Every note folder path in the vault.',
  'notes.exists': 'Whether a note with this title or path exists.',
  'notes.getPropertyDefinitions': 'Every property definition: name, type, options and colors.',
  'notes.listAttachments': 'The files stored in a note’s attachments folder.',
  'notes.getFolderConfig': 'A folder’s settings, such as its icon and default template.',
  'notes.getFolderTemplate': 'The template a new note in this folder starts from, if any.',
  'notes.getVersions': 'The saved versions (snapshots) of a note, newest first.',
  'notes.getVersion': 'One saved version of a note, with its content.',
  'notes.getPositions': 'The manual sort order of the notes in one folder.',
  'notes.getAllPositions': 'The manual sort order of notes in every folder.',
  'notes.getLocalOnlyCount': 'How many notes are kept on this device only and never synced.',
  'notes.getCalendarPropertyNames': 'The date properties shown on the calendar.',

  'tasks.get': 'Read a task by id.',
  'tasks.list':
    'List tasks, filtered by project, status, due date or completion, sorted and paged.',
  'tasks.getSubtasks': 'The subtasks of a task.',
  'tasks.getProject': 'Read a project by id, with its statuses.',
  'tasks.listProjects': 'Every project with its task counts.',
  'tasks.listStatuses': 'The statuses of a project, in board order.',
  'tasks.getTags': 'Every tag used on tasks, with how many tasks carry it.',
  'tasks.getStats': 'Task counts: total, completed, overdue, due today and this week.',
  'tasks.getToday': 'Tasks due today, plus overdue ones.',
  'tasks.getUpcoming': 'Tasks due in the next number of days (7 by default), grouped by day.',
  'tasks.getOverdue': 'Open tasks whose due date has passed.',
  'tasks.getLinkedTasks': 'Tasks linked to a note.',
  'tasks.listProjectLinks': 'The raw link rows of a project’s hub, including pin state.',
  'tasks.listProjectContents': 'The notes, files and events a project holds.',
  'tasks.listForItem': 'The projects a note, file or calendar event belongs to.',

  'inbox.get': 'Read an inbox item by id.',
  'inbox.list': 'List inbox items, filtered by type and paged.',
  'inbox.previewLink': 'Fetch a URL’s title, description and image without capturing it.',
  'inbox.getSuggestions':
    'Where to file an inbox item: suggested folders and notes with confidence.',
  'inbox.getTags': 'Every tag used on inbox items, with counts.',
  'inbox.getSnoozed': 'Inbox items that are snoozed, with when they come back.',
  'inbox.getStats': 'Inbox counts: items, items by type, and items captured and filed today.',
  'inbox.getJobs': 'Background jobs on inbox items, such as transcription and metadata fetches.',
  'inbox.getPatterns': 'Capture patterns over time: heatmap, by-type breakdown and peak hours.',
  'inbox.getStaleThreshold': 'After how many days an unfiled inbox item counts as stale.',
  'inbox.listArchived': 'Archived inbox items, searchable and paged.',
  'inbox.getFilingHistory': 'Recently filed inbox items and where each went.',

  'journal.getEntry': 'Read the journal entry for a date (YYYY-MM-DD); null when there is none.',
  'journal.getHeatmap': 'Per-day writing activity for a year, for the journal heatmap.',
  'journal.getMonthEntries': 'The journal entries of one month, with previews.',
  'journal.getYearStats': 'Per-month journal statistics for a year.',
  'journal.getDayContext': 'What else happened on a date: tasks due and calendar events.',
  'journal.getAllTags': 'Every tag used in journal entries, with counts.',
  'journal.getStreak': 'The current and longest daily journaling streak.',
  'properties.get': 'The properties (frontmatter fields) of a note or journal entry.',
  'templates.list': 'Every note template.',
  'templates.get': 'Read a template by id, with its content and properties.',
  'savedFilters.list': 'Every saved task filter.',
  'bookmarks.get': 'Read a bookmark by id.',
  'bookmarks.list': 'List bookmarks, optionally of one item type.',
  'bookmarks.isBookmarked': 'Whether an item is bookmarked.',
  'bookmarks.listByType': 'The bookmarks of one item type.',
  'bookmarks.getByItem': 'The bookmark of an item, or null.',
  'tags.getNotesByTag': 'The notes that carry a tag, pinned notes first.',
  'tags.getAllWithCounts': 'Every tag with its color, icon, category and note count.',
  'tags.listCategories': 'Every tag category with its sort order and tag count.',
  'folderView.getConfig': 'A folder view’s saved configuration.',
  'folderView.getViews': 'The saved views of a folder or tag scope.',
  'folderView.listWithProperties':
    'The notes in a folder or tag scope with the values of the properties asked for.',
  'folderView.getAvailableProperties': 'The properties used by notes in a folder or tag scope.',
  'folderView.getFolderSuggestions': 'Folders a note would fit in, best first.',
  'folderView.folderExists': 'Whether a folder exists.',
  'reminders.get': 'Read a reminder by id.',
  'reminders.list': 'List reminders, filtered by target or status.',
  'reminders.getUpcoming': 'Reminders due in the next number of days (7 by default).',
  'reminders.getDue': 'Reminders that are due now.',
  'reminders.getForTarget': 'The reminders set on a note, journal entry or highlight.',
  'reminders.countPending': 'How many reminders are still pending.',

  'calendar.getEvent': 'Read a calendar event by id.',
  'calendar.listEvents': 'List memrynote calendar events.',
  'calendar.getRange':
    'Calendar items (events, tasks, reminders) between two times, or on one YYYY-MM-DD day.',

  'settings.get': 'Read one stored setting by key; null when it is not set.',
  'settings.getJournalSettings': 'Journal settings: templates and which panels show.',
  'settings.getAISettings': 'Whether AI features are on.',
  'settings.getVoiceTranscriptionSettings': 'Voice transcription settings: provider and model.',
  'settings.getVoiceModelStatus': 'Whether the local voice model is downloaded and ready.',
  'settings.getVoiceRecordingReadiness': 'Whether voice recording can start now, and why not.',
  'settings.getVoiceTranscriptionOpenAIKeyStatus':
    'Whether an OpenAI key for transcription is stored. The key itself is never returned.',
  'settings.getAIModelStatus': 'The state of the local embedding model.',
  'settings.getTabSettings': 'Tab settings.',
  'settings.getNoteEditorSettings': 'Note editor toolbar settings.',
  'settings.getGeneralSettings': 'General settings: theme, fonts, language and startup.',
  'settings.getEditorSettings': 'Editor settings: width, spell check, checklists and more.',
  'settings.getTaskSettings': 'Task settings: default project, sort order and week start.',
  'settings.getKeyboardSettings': 'Keyboard shortcut overrides.',
  'settings.getSyncSettings': 'Sync settings.',
  'settings.getBackupSettings': 'Backup settings.',
  'settings.getGraphSettings': 'Graph view settings.',
  'settings.getCalendarSettings': 'Calendar settings.',
  'settings.getFeaturesSettings':
    'Which surfaces are on: home, inbox, journal, tasks, calendar, graph and spatial canvas.',
  'settings.getInboxSettings': 'Inbox settings, such as the daily review reminder.',

  'search.query': 'Full-text search across notes, tasks, journal entries and inbox items.',
  'search.quick': 'The fast search behind the command palette: a few hits per type.',
  'search.getStats': 'Search index statistics.',
  'search.getReasons': 'Recently opened search results and why they were opened.',
  'search.getAllTags': 'Every tag known to search, with counts.',
  'graph.getData': 'The whole link graph: nodes and edges.',
  'graph.getLocal': 'The link graph around one note, to a depth.',
  'homePages.list': 'Every home page.',
  'homePages.get': 'Read a home page by id.',
  'vault.getAll': 'The vaults known on this device and which one is open.',
  'vault.getStatus': 'The open vault’s state: path, indexing progress and errors.',
  'vault.getConfig': 'The open vault’s configuration.',
  'vault.listAccount': 'The vaults of the signed-in account on the sync server.',
  'canvas.list': 'Every canvas.',
  'canvas.getAsset': 'One image file attached to a canvas.',
  'canvas.listAssets': 'The image files attached to a canvas.',
  'canvas.libraryList': 'The shapes saved in the canvas library.',

  'notes.create': 'Create a note from markdown, in a folder, with tags and properties.',
  'notes.update': 'Change a note’s title, content, tags, properties or emoji.',
  'notes.rename': 'Rename a note.',
  'notes.move': 'Move a note to another folder.',
  'notes.delete': 'Delete a note.',
  'notes.createFolder': 'Create a note folder.',
  'notes.renameFolder': 'Rename or move a note folder and everything in it.',
  'notes.deleteFolder': 'Delete a note folder and everything in it.',
  'notes.createPropertyDefinition': 'Define a property: its name, type and options.',
  'notes.updatePropertyDefinition': 'Change a property definition’s type, options or color.',
  'notes.ensurePropertyDefinition':
    'Define a status, select or multiselect property if it does not exist yet.',
  'notes.addPropertyOption': 'Add an option to a select or multiselect property.',
  'notes.addStatusOption': 'Add an option to one category of a status property.',
  'notes.removePropertyOption': 'Remove an option from a property.',
  'notes.renamePropertyOption': 'Rename a property option, in every note that uses it.',
  'notes.updateOptionColor': 'Change the color of a property option.',
  'notes.deletePropertyDefinition': 'Delete a property definition.',
  'notes.uploadAttachment':
    'Attach a file to a note. JSON cannot carry the file, so this fails for agents.',
  'notes.deleteAttachment': 'Delete a file from a note’s attachments folder.',
  'notes.setFolderConfig': 'Change a folder’s settings, such as its icon and default template.',
  'notes.restoreVersion': 'Restore a note to a saved version.',
  'notes.deleteVersion': 'Delete a saved version of a note.',
  'notes.reorder': 'Set the manual order of the notes in a folder.',
  'notes.importFiles': 'Copy files from paths on this device into the vault as notes or files.',
  'notes.setLocalOnly': 'Keep a note on this device only, or let it sync again.',
  'notes.setCalendarPropertyVisibility': 'Show or hide a date property on the calendar.',
  'notes.applyTemplate': 'Apply a template to an existing note.',
  'notes.exportPdf':
    'Export a note to a PDF file at outputPath; without outputPath the user picks the file.',
  'notes.exportHtml':
    'Export a note to an HTML file at outputPath; without outputPath the user picks the file.',

  'tasks.create': 'Create a task in a project.',
  'tasks.update': 'Change a task’s fields.',
  'tasks.delete': 'Delete a task.',
  'tasks.complete': 'Mark a task done.',
  'tasks.uncomplete': 'Mark a done task open again.',
  'tasks.archive': 'Archive a task.',
  'tasks.unarchive': 'Bring an archived task back.',
  'tasks.move': 'Move a task to another project, status or parent, at a position.',
  'tasks.reorder': 'Set the positions of tasks.',
  'tasks.duplicate': 'Copy a task.',
  'tasks.convertToSubtask': 'Make a task a subtask of another task.',
  'tasks.convertToTask': 'Make a subtask a top-level task.',
  'tasks.createProject': 'Create a project, with its statuses.',
  'tasks.updateProject': 'Change a project’s name, description, color, icon or statuses.',
  'tasks.deleteProject': 'Delete a project and its tasks.',
  'tasks.archiveProject': 'Archive a project.',
  'tasks.reorderProjects': 'Set the order of projects.',
  'tasks.linkProjectItem': 'Link a note, file or calendar event to a project.',
  'tasks.unlinkProjectItem': 'Unlink a note, file or calendar event from a project.',
  'tasks.setProjectLinkPinned': 'Pin or unpin a linked item in a project’s hub.',
  'tasks.setProjectHomeNote': 'Set or clear (null) a project’s home note.',
  'tasks.captureUrlToProject': 'Save a web page as a bookmark note linked to a project.',
  'tasks.importFilesToProject':
    'Import files from this device into the vault, linked to a project.',
  'tasks.createStatus': 'Add a status to a project.',
  'tasks.updateStatus': 'Change a status’s name, color, position or done state.',
  'tasks.deleteStatus': 'Delete a status.',
  'tasks.reorderStatuses': 'Set the order of a project’s statuses.',
  'tasks.bulkComplete': 'Mark several tasks done.',
  'tasks.bulkDelete': 'Delete several tasks.',
  'tasks.bulkMove': 'Move several tasks to a project.',
  'tasks.bulkArchive': 'Archive several tasks.',

  'inbox.captureText': 'Capture a text note into the inbox.',
  'inbox.captureLink': 'Capture a link into the inbox; its title and preview are fetched.',
  'inbox.captureImage':
    'Capture an image, audio, video or PDF file into the inbox. Over JSON, data is the bytes as an object of byte values: { "0": 137, "1": 80, ... }.',
  'inbox.captureVoice':
    'Capture a voice memo into the inbox. Over JSON, data is the bytes as an object of byte values: { "0": 26, "1": 69, ... }.',
  'inbox.captureClip':
    'Web clips are not built yet: this replies { success: false, error: "Not implemented yet" }.',
  'inbox.capturePdf':
    'Capture a PDF into the inbox. data must be a Buffer, which JSON cannot carry, so this fails for agents; use inbox.captureImage with mimeType application/pdf.',
  'inbox.update': 'Change an inbox item’s title or content.',
  'inbox.archive': 'Archive an inbox item.',
  'inbox.file': 'File an inbox item into a folder or note.',
  'inbox.trackSuggestion': 'Record whether a filing suggestion was taken, to improve later ones.',
  'inbox.convertToNote': 'Turn an inbox item into a note.',
  'inbox.convertToTask': 'Turn an inbox item into a task.',
  'inbox.convertToEvent': 'Turn an inbox item into a calendar event.',
  'inbox.convertToReminder': 'Turn an inbox item into a reminder.',
  'inbox.linkToNote': 'Append an inbox item to a note and file it there.',
  'inbox.addTag': 'Add a tag to an inbox item.',
  'inbox.removeTag': 'Remove a tag from an inbox item.',
  'inbox.snooze': 'Hide an inbox item until a time.',
  'inbox.unsnooze': 'Bring a snoozed inbox item back now.',
  'inbox.markViewed': 'Mark an inbox item as viewed.',
  'inbox.bulkFile': 'File several inbox items into one place.',
  'inbox.bulkArchive': 'Archive several inbox items.',
  'inbox.bulkTag': 'Add tags to several inbox items.',
  'inbox.bulkSnooze': 'Snooze several inbox items until a time.',
  'inbox.fileAllStale': 'File every stale inbox item into the Unsorted folder.',
  'inbox.retryTranscription': 'Run transcription of a voice memo again.',
  'inbox.retryMetadata': 'Fetch a link’s title and preview again.',
  'inbox.setStaleThreshold': 'Set after how many days an unfiled inbox item counts as stale.',
  'inbox.unarchive': 'Bring an archived inbox item back.',
  'inbox.deletePermanent': 'Delete an archived inbox item for good.',
  'inbox.undoFile': 'Undo filing an inbox item.',
  'inbox.undoArchive': 'Undo archiving an inbox item.',

  'journal.createEntry': 'Create the journal entry for a date.',
  'journal.updateEntry': 'Change the content, tags or properties of a journal entry.',
  'journal.deleteEntry': 'Delete the journal entry for a date.',
  'properties.set':
    'Replace the whole property record of a note or journal entry; a property left out is deleted.',
  'properties.rename': 'Rename a property on one note or journal entry.',
  'templates.create': 'Create a note template.',
  'templates.update': 'Change a template.',
  'templates.delete': 'Delete a template.',
  'templates.duplicate': 'Copy a template under a new name.',
  'savedFilters.create': 'Save a task filter.',
  'savedFilters.update': 'Change a saved task filter.',
  'savedFilters.delete': 'Delete a saved task filter.',
  'savedFilters.reorder': 'Set the order of saved task filters.',
  'bookmarks.create': 'Bookmark an item.',
  'bookmarks.delete': 'Delete a bookmark.',
  'bookmarks.toggle': 'Bookmark an item, or remove its bookmark when it has one.',
  'bookmarks.reorder': 'Set the order of bookmarks.',
  'bookmarks.bulkDelete': 'Delete several bookmarks.',
  'bookmarks.bulkCreate': 'Bookmark several items.',
  'tags.pinNoteToTag': 'Pin a note to the top of a tag’s note list.',
  'tags.unpinNoteFromTag': 'Unpin a note from a tag.',
  'tags.renameTag': 'Rename a tag everywhere it is used.',
  'tags.updateTagColor': 'Change a tag’s color.',
  'tags.deleteTag': 'Remove a tag from every note that carries it.',
  'tags.removeTagFromNote': 'Remove a tag from one note.',
  'tags.mergeTag': 'Merge one tag into another; notes with the first get the second.',
  'tags.updateTagIcon': 'Change a tag’s icon.',
  'tags.createCategory': 'Create a tag category.',
  'tags.renameCategory': 'Rename a tag category.',
  'tags.deleteCategory': 'Delete a tag category; its tags become uncategorized.',
  'tags.reorder':
    'Move tags into categories and order tags and categories; the only way to categorize a tag.',
  'folderView.setConfig': 'Save a folder view’s configuration.',
  'folderView.setView': 'Create or change a saved view of a folder or tag scope.',
  'folderView.deleteView': 'Delete a saved view.',
  'reminders.create': 'Set a reminder on a note, journal entry or highlight.',
  'reminders.update': 'Change a reminder’s time, title or note.',
  'reminders.delete': 'Delete a reminder.',
  'reminders.dismiss': 'Dismiss a reminder that fired.',
  'reminders.snooze': 'Snooze a reminder until a time.',
  'reminders.bulkDismiss': 'Dismiss several reminders.',
  'calendar.createEvent': 'Create a memrynote calendar event.',
  'calendar.updateEvent': 'Change a memrynote calendar event.',
  'calendar.deleteEvent': 'Delete a memrynote calendar event.',

  'settings.set': 'Store one setting by key, as a string.',
  'settings.setJournalSettings': 'Change journal settings.',
  'settings.setAISettings': 'Turn AI features on or off.',
  'settings.setVoiceTranscriptionSettings': 'Change voice transcription settings.',
  'settings.setTabSettings': 'Change tab settings.',
  'settings.setNoteEditorSettings': 'Change the note editor toolbar mode.',
  'settings.setGeneralSettings': 'Change general settings; any subset of them.',
  'settings.setEditorSettings': 'Change editor settings; any subset of them.',
  'settings.setTaskSettings': 'Change task settings; any subset of them.',
  'settings.setKeyboardSettings': 'Change keyboard shortcut overrides.',
  'settings.resetKeyboardSettings': 'Reset every keyboard shortcut to its default.',
  'settings.setSyncSettings': 'Change sync settings.',
  'settings.setBackupSettings': 'Change backup settings.',
  'settings.setGraphSettings': 'Change graph view settings.',
  'settings.setCalendarSettings': 'Change calendar settings.',
  'settings.setFeaturesSettings': 'Turn surfaces on or off: home, inbox, journal, tasks and more.',
  'settings.setInboxSettings': 'Change inbox settings.',

  'search.rebuildIndex': 'Rebuild the search index from the vault files.',
  'search.addReason': 'Record that a search result was opened, for recent results.',
  'search.clearReasons': 'Forget the recently opened search results.',
  'homePages.create': 'Create a home page.',
  'homePages.update': 'Change a home page.',
  'homePages.delete': 'Delete a home page.',
  'homePages.reorder': 'Set the order of home pages.',
  'vault.switch': 'Open another vault by path. The agent’s session ends with the old vault.',
  'vault.reindex': 'Re-index the open vault from its files.',
  'vault.updateConfig': 'Change the open vault’s configuration.',
  'vault.downloadRemote': 'Download a vault of the signed-in account from the sync server.',
  'canvas.create': 'Create an empty canvas.',
  'canvas.delete': 'Delete a canvas.'
} as const satisfies Record<AgentMcpDesktopOperation, string>

export function desktopOperationSummary(operation: AgentMcpDesktopOperation): string {
  return AGENT_DESKTOP_OPERATION_SUMMARIES[operation]
}
