//! The `attachment-manifest` conformance class, chapter 14 §14.4 (N205, Q3).
//!
//! Q3 asked whether this core reimplements manifest signing or whether the
//! logic is lifted somewhere both ports call. There is no such place — this is
//! a standalone Rust port a Swift shell links as a static library, and it
//! cannot call `packages/sync-client/src/push/attachment-manifest.ts`. So it
//! reimplements, and this file is what stops the two from drifting.
//!
//! Nothing here recomputes an expectation. The committed JSON is generated by
//! the TypeScript writer and is the only input (README rule 2).

mod support;

use memry_core::protocol::attachment_manifest::{
    AttachmentChunkRef, AttachmentManifest, EncryptedAttachmentManifest, ManifestError, decrypt,
    encrypt, manifest_json,
};
use serde_json::Value as Json;
use support::{hex_field, str_field, vector_file};

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as BASE64_STANDARD;

fn b64(value: &str) -> Vec<u8> {
    BASE64_STANDARD.decode(value).expect("a base64 field")
}

fn envelope_of(case: &Json) -> EncryptedAttachmentManifest {
    let node = &case["envelope"];
    EncryptedAttachmentManifest {
        encrypted_manifest: str_field(node, "encryptedManifest").to_owned(),
        manifest_nonce: str_field(node, "manifestNonce").to_owned(),
        encrypted_file_key: str_field(node, "encryptedFileKey").to_owned(),
        key_nonce: str_field(node, "keyNonce").to_owned(),
        manifest_signature: str_field(node, "manifestSignature").to_owned(),
        signer_device_id: str_field(node, "signerDeviceId").to_owned(),
    }
}

fn manifest_of(case: &Json) -> AttachmentManifest {
    let node = &case["manifest"];
    AttachmentManifest {
        id: str_field(node, "id").to_owned(),
        filename: str_field(node, "filename").to_owned(),
        mime_type: str_field(node, "mimeType").to_owned(),
        size: node["size"].as_u64().expect("size"),
        checksum: str_field(node, "checksum").to_owned(),
        chunks: node["chunks"]
            .as_array()
            .expect("chunks")
            .iter()
            .map(|chunk| AttachmentChunkRef {
                index: chunk["index"].as_u64().expect("index") as u32,
                hash: str_field(chunk, "hash").to_owned(),
                encrypted_hash: str_field(chunk, "encryptedHash").to_owned(),
                size: chunk["size"].as_u64().expect("chunk size"),
            })
            .collect(),
        chunk_size: node["chunkSize"].as_u64().expect("chunkSize"),
        created_at: node["createdAt"].as_i64().expect("createdAt"),
    }
}

/// The reader half: every committed envelope opens, and yields the manifest
/// the file records.
#[test]
fn every_committed_envelope_decrypts_to_its_manifest() {
    let file = vector_file("attachment-manifest");
    let vault_key = hex_field(&file["meta"], "vaultKeyHex");
    let signer_public_key = b64(str_field(&file["meta"], "signerPublicKeyB64"));
    let cases = file["cases"].as_array().expect("cases");
    assert_eq!(
        cases.len() as u64,
        file["meta"]["caseCount"].as_u64().expect("caseCount")
    );

    for case in cases {
        let name = str_field(case, "name");
        let (manifest, file_key) = decrypt(&envelope_of(case), &vault_key, &signer_public_key)
            .unwrap_or_else(|error| panic!("{name}: {error}"));

        assert_eq!(
            manifest,
            manifest_of(case),
            "{name}: {}",
            str_field(case, "pins")
        );
        assert_eq!(
            file_key.as_slice(),
            hex_field(&file["meta"], "fileKeyHex").as_slice(),
            "{name}: the unwrapped file key"
        );
    }
}

/// The writer half: this port produces the **same envelope bytes**, which is
/// what makes the signature interoperable rather than merely self-consistent.
#[test]
fn this_port_writes_the_same_envelope() {
    let file = vector_file("attachment-manifest");
    let meta = &file["meta"];
    let vault_key = hex_field(meta, "vaultKeyHex");
    let file_key = hex_field(meta, "fileKeyHex");
    let manifest_nonce = hex_field(meta, "manifestNonceHex");
    let key_nonce = hex_field(meta, "keyNonceHex");
    let seed = hex_field(meta, "signerSeedHex");
    let (_, secret_key) = memry_core::crypto::sodium::sign_seed_keypair(&seed).expect("keypair");
    let device_id = str_field(meta, "signerDeviceId");

    for case in file["cases"].as_array().expect("cases") {
        let name = str_field(case, "name");
        let produced = encrypt(
            &manifest_of(case),
            &file_key,
            &vault_key,
            &manifest_nonce,
            &key_nonce,
            &secret_key,
            device_id,
        )
        .unwrap_or_else(|error| panic!("{name}: {error}"));

        assert_eq!(produced, envelope_of(case), "{name}: the envelope bytes");
    }
}

/// The manifest body, byte for byte.
///
/// The signature covers the four envelope fields and **not** the body, so a
/// port that emitted the same fields in a different order would produce a
/// manifest the other port still parses and nothing would fail. This is the
/// assertion that catches that.
#[test]
fn the_manifest_json_is_byte_identical_to_the_reference_writers() {
    let file = vector_file("attachment-manifest");
    for case in file["cases"].as_array().expect("cases") {
        let name = str_field(case, "name");
        let produced =
            String::from_utf8(manifest_json(&manifest_of(case)).expect("json")).expect("utf8");
        assert_eq!(
            produced,
            str_field(case, "manifestJson"),
            "{name}: the manifest body the signature does NOT cover"
        );
    }
}

/// §14.4.1's order, which is behaviour rather than bytes.
///
/// Each mutation leaves a well-formed envelope whose signature no longer
/// matches. A reader that unwrapped and decrypted first would either succeed
/// on attacker-chosen bytes or report a decrypt failure; the only correct
/// answer is a signature refusal, and it must name the signer.
#[test]
fn a_tampered_envelope_is_refused_on_the_signature() {
    let file = vector_file("attachment-manifest");
    let vault_key = hex_field(&file["meta"], "vaultKeyHex");
    let signer_public_key = b64(str_field(&file["meta"], "signerPublicKeyB64"));
    let case = &file["cases"].as_array().expect("cases")[0];

    // A server-side swap of each signed field in turn. The manifest is the
    // only thing that names the file, so this is exactly the attack §14.4.1
    // exists against.
    /// One server-side swap: the field it touches, and how.
    type Swap = (&'static str, fn(&mut EncryptedAttachmentManifest));

    let swaps: [Swap; 4] = [
        ("encryptedManifest", |envelope| {
            envelope.encrypted_manifest = BASE64_STANDARD.encode(b"someone else's manifest");
        }),
        ("manifestNonce", |envelope| {
            envelope.manifest_nonce = BASE64_STANDARD.encode([9u8; 24]);
        }),
        ("encryptedFileKey", |envelope| {
            envelope.encrypted_file_key = BASE64_STANDARD.encode([9u8; 48]);
        }),
        ("keyNonce", |envelope| {
            envelope.key_nonce = BASE64_STANDARD.encode([9u8; 24]);
        }),
    ];

    for (field, swap) in swaps {
        let mut envelope = envelope_of(case);
        swap(&mut envelope);
        match decrypt(&envelope, &vault_key, &signer_public_key) {
            Err(ManifestError::BadSignature { signer_device_id }) => {
                assert_eq!(signer_device_id, envelope_of(case).signer_device_id);
            }
            other => panic!("swapping {field} must be a signature refusal, got {other:?}"),
        }
    }
}

/// An unresolvable signer is a hard failure, not a fallback (§14.4.1).
///
/// The core enforces that by signature: `decrypt` takes the signer's public
/// key and cannot be called without one. The nearest reachable mistake is
/// calling it with the **wrong** device's key, which must refuse.
#[test]
fn a_manifest_verified_against_the_wrong_device_is_refused() {
    let file = vector_file("attachment-manifest");
    let vault_key = hex_field(&file["meta"], "vaultKeyHex");
    let (other_public, _) =
        memry_core::crypto::sodium::sign_seed_keypair(&[0x5c; 32]).expect("keypair");
    let case = &file["cases"].as_array().expect("cases")[0];

    assert!(matches!(
        decrypt(&envelope_of(case), &vault_key, &other_public),
        Err(ManifestError::BadSignature { .. })
    ));
}

/// §14.9: a reader sizes chunks from `chunks[j].size`, never from `chunkSize`.
///
/// The class carries a writer that chose 2 bytes, so a port that hardcoded
/// 8 MiB reads that file wrong. Asserted here rather than left implicit,
/// because the failure would be a truncated download rather than an error.
#[test]
fn a_reader_does_not_assume_the_desktop_chunk_size() {
    let file = vector_file("attachment-manifest");
    let vault_key = hex_field(&file["meta"], "vaultKeyHex");
    let signer_public_key = b64(str_field(&file["meta"], "signerPublicKeyB64"));

    let case = file["cases"]
        .as_array()
        .expect("cases")
        .iter()
        .find(|case| str_field(case, "name") == "a writer that chose a different chunk size")
        .expect("the odd-chunk-size case");

    let (manifest, _) = decrypt(&envelope_of(case), &vault_key, &signer_public_key).expect("open");
    assert_ne!(manifest.chunk_size, 8 * 1024 * 1024);
    // The sum of the per-chunk sizes is the file, and it is not a multiple of
    // the declared chunk size.
    let total: u64 = manifest.chunks.iter().map(|chunk| chunk.size).sum();
    assert_eq!(total, manifest.size);
}
