//! The `delete-attestation` conformance class, chapter 04 §4.8.4 (#2408).
//!
//! The committed JSON is generated by the TypeScript writer and is the only
//! input (README rule 2). The core reimplements the message and the signer,
//! so this file is what stops the two ports from drifting: a divergence would
//! make every attestation this core pushes fail the server's per-item check.

mod support;

use memry_core::crypto::cbor::field_order;
use memry_core::crypto::sodium;
use memry_core::protocol::delete_attestation::{
    DeleteClaim, PURPOSE, claim_of, message, sign, verify,
};
use memry_core::protocol::envelope::SyncOperation;
use memry_core::sync::clock::VectorClock;
use serde_json::Value as Json;
use support::{hex_field, str_field, vector_file};

use base64::Engine as _;
use base64::engine::general_purpose::STANDARD as BASE64_STANDARD;

fn b64(value: &str) -> Vec<u8> {
    BASE64_STANDARD.decode(value).expect("a base64 field")
}

fn clock_of(node: &Json) -> VectorClock {
    serde_json::from_value(node.clone()).expect("a clock")
}

/// Runs `f` over the claim a vector node spells.
fn with_claim<T>(node: &Json, f: impl FnOnce(&DeleteClaim<'_>) -> T) -> T {
    let clock = clock_of(&node["clock"]);
    f(&DeleteClaim {
        item_type: str_field(node, "type"),
        item_id: str_field(node, "id"),
        clock: &clock,
        deleted_at: node["deletedAt"].as_i64().expect("deletedAt"),
    })
}

// #2408
#[test]
fn the_purpose_and_allowlist_match_the_file() {
    let file = vector_file("delete-attestation");
    assert_eq!(str_field(&file["meta"], "purpose"), PURPOSE);
    let order: Vec<&str> = file["meta"]["fieldOrder"]
        .as_array()
        .expect("fieldOrder")
        .iter()
        .map(|name| name.as_str().expect("a name"))
        .collect();
    assert_eq!(order, field_order::DELETE_ATTESTATION);
    assert_eq!(
        field_order::by_name("DELETE_ATTESTATION"),
        Some(field_order::DELETE_ATTESTATION)
    );
}

// #2408: the same message bytes and, Ed25519 being deterministic, the same
// signature, for seconds and milliseconds, both clock orders and a UTF-8 id.
#[test]
fn every_case_reproduces_the_message_and_the_signature_byte_for_byte() {
    let file = vector_file("delete-attestation");
    let meta = &file["meta"];
    let (public, secret) =
        sodium::sign_seed_keypair(&hex_field(meta, "signerSeedHex")).expect("a keypair");
    assert_eq!(public, b64(str_field(meta, "signerPublicKeyB64")));

    let cases = file["cases"].as_array().expect("cases");
    for case in cases {
        let name = str_field(case, "name");
        with_claim(&case["claim"], |claim| {
            assert_eq!(
                message(claim).expect("encodes"),
                hex_field(case, "messageHex"),
                "{name}"
            );
            assert_eq!(
                sign(claim, &secret).expect("signs"),
                str_field(case, "signatureB64"),
                "{name}"
            );
            verify(claim, str_field(case, "signatureB64"), &public)
                .unwrap_or_else(|error| panic!("{name}: {error}"));
        });
    }
    assert_eq!(cases.len() as u64, meta["caseCount"].as_u64().unwrap());
}

// #2408: forged or mismatched attestations never verify.
#[test]
fn every_mutation_is_refused() {
    let file = vector_file("delete-attestation");
    let mutations = file["mutations"].as_array().expect("mutations");
    assert!(!mutations.is_empty());
    for mutation in mutations {
        let name = str_field(mutation, "name");
        let key = b64(str_field(mutation, "signerPublicKeyB64"));
        with_claim(&mutation["claim"], |claim| {
            assert!(
                verify(claim, str_field(mutation, "signatureB64"), &key).is_err(),
                "{name} verified"
            );
        });
    }
}

// #2408: the eligibility rule is the TypeScript `deleteClaimOf`.
#[test]
fn claim_of_agrees_with_the_shared_rule() {
    let file = vector_file("delete-attestation");
    for entry in file["claimOf"].as_array().expect("claimOf") {
        let name = str_field(entry, "name");
        let input = &entry["input"];
        let clock = (!input["clock"].is_null()).then(|| clock_of(&input["clock"]));
        let claim = claim_of(
            str_field(input, "type"),
            str_field(input, "id"),
            SyncOperation::from_wire(Some(str_field(input, "operation"))).expect("an operation"),
            clock.as_ref(),
            input["deletedAt"].as_i64(),
        );
        match &entry["claim"] {
            Json::Null => assert!(claim.is_none(), "{name}"),
            expected => {
                let claim = claim.unwrap_or_else(|| panic!("{name}: no claim"));
                assert_eq!(claim.item_type, str_field(expected, "type"), "{name}");
                assert_eq!(claim.item_id, str_field(expected, "id"), "{name}");
                assert_eq!(*claim.clock, clock_of(&expected["clock"]), "{name}");
                assert_eq!(Some(claim.deleted_at), expected["deletedAt"].as_i64());
            }
        }
    }
}
