//! The `recurrence` and `repeatPhrase.firstOccurrence` sections of the
//! `task-parsing` committed vectors (spec 004 D3, D5).
//!
//! Rule 2 of `packages/contracts/test-vectors/README.md`: the committed JSON is
//! the only input. Every expected value is read out of the file, generated by
//! desktop's `packages/domain-tasks/src/parsing/recurrence.ts` and
//! `repeat-phrase.ts`. Each test checks every case in its section and panics
//! once, listing every mismatch, so one run shows the whole gap.

mod support;

use memry_core::domain::calendar::{CivilDate, LocalDateTime};
use memry_core::domain::recurrence::{
    RepeatCompletion, RepeatProgress, calculate_next_occurrence, calculate_next_occurrences,
    complete_repeating_task, find_nth_weekday_of_month, first_occurrence_for, repeat_progress,
    should_create_next_occurrence,
};
use memry_core::domain::repeat_config::RepeatConfig;
use serde_json::{Value as Json, json};
use support::vector_file;

fn recurrence_section(name: &str) -> (Json, Vec<Json>) {
    let vectors = vector_file("task-parsing");
    let cases = vectors["recurrence"][name]
        .as_array()
        .unwrap_or_else(|| panic!("recurrence.{name} is an array"))
        .clone();
    assert!(!cases.is_empty(), "recurrence.{name} has cases");
    (vectors, cases)
}

/// The named wire config under `recurrence.configs`, read the way desktop does.
fn config(vectors: &Json, case: &Json) -> RepeatConfig {
    let name = case["config"].as_str().expect("config name");
    let wire = &vectors["recurrence"]["configs"][name];
    RepeatConfig::from_wire(wire).unwrap_or_else(|| panic!("config {name} reads: {wire}"))
}

fn date(value: &Json) -> CivilDate {
    let key = value.as_str().expect("date key");
    CivilDate::parse_key(key).unwrap_or_else(|| panic!("date key {key}"))
}

fn instant(value: &Json) -> LocalDateTime {
    let text = value.as_str().expect("instant");
    LocalDateTime::parse(text).unwrap_or_else(|| panic!("instant {text}"))
}

fn date_json(date: Option<CivilDate>) -> Json {
    date.map_or(Json::Null, |date| json!(date.key()))
}

fn report(section: &str, total: usize, failures: &[String]) {
    assert!(
        failures.is_empty(),
        "{} of {total} {section} cases differ:\n{}",
        failures.len(),
        failures.join("\n")
    );
}

#[test]
fn recurrence_next_matches_desktop() {
    let (vectors, cases) = recurrence_section("next");
    let mut failures = Vec::new();
    for case in &cases {
        let actual = date_json(calculate_next_occurrence(
            date(&case["from"]),
            &config(&vectors, case),
        ));
        if actual != case["expected"] {
            failures.push(format!("{case} -> actual {actual}"));
        }
    }
    report("recurrence.next", cases.len(), &failures);
}

#[test]
fn recurrence_occurrences_match_desktop() {
    let (vectors, cases) = recurrence_section("occurrences");
    let mut failures = Vec::new();
    for case in &cases {
        let count = usize::try_from(case["count"].as_u64().expect("count")).expect("count fits");
        let actual: Vec<Json> =
            calculate_next_occurrences(date(&case["start"]), &config(&vectors, case), count)
                .into_iter()
                .map(|date| json!(date.key()))
                .collect();
        let actual = Json::Array(actual);
        if actual != case["expected"] {
            failures.push(format!("{case} -> actual {actual}"));
        }
    }
    report("recurrence.occurrences", cases.len(), &failures);
}

#[test]
fn recurrence_should_create_matches_desktop() {
    let (vectors, cases) = recurrence_section("shouldCreate");
    let mut failures = Vec::new();
    for case in &cases {
        let actual = json!(should_create_next_occurrence(
            &config(&vectors, case),
            instant(&case["now"]),
        ));
        if actual != case["expected"] {
            failures.push(format!("{case} -> actual {actual}"));
        }
    }
    report("recurrence.shouldCreate", cases.len(), &failures);
}

#[test]
fn recurrence_complete_matches_desktop() {
    let (vectors, cases) = recurrence_section("complete");
    let mut failures = Vec::new();
    for case in &cases {
        let RepeatCompletion {
            next_due_date,
            completed_count,
        } = complete_repeating_task(
            date(&case["due"]),
            &config(&vectors, case),
            case["repeatFrom"].as_str(),
            instant(&case["completedAt"]),
        );
        let actual = json!({
            "nextDueDate": date_json(next_due_date),
            "completedCount": completed_count,
        });
        if actual != case["expected"] {
            failures.push(format!("{case} -> actual {actual}"));
        }
    }
    report("recurrence.complete", cases.len(), &failures);
}

#[test]
fn recurrence_nth_weekday_matches_desktop() {
    let (_, cases) = recurrence_section("nthWeekday");
    let mut failures = Vec::new();
    for case in &cases {
        let day_of_week =
            u32::try_from(case["dayOfWeek"].as_u64().expect("dayOfWeek")).expect("dayOfWeek fits");
        let actual = json!(
            find_nth_weekday_of_month(
                case["year"].as_i64().expect("year"),
                case["month"].as_i64().expect("month"),
                case["nth"].as_i64().expect("nth"),
                day_of_week,
            )
            .key()
        );
        if actual != case["expected"] {
            failures.push(format!("{case} -> actual {actual}"));
        }
    }
    report("recurrence.nthWeekday", cases.len(), &failures);
}

#[test]
fn recurrence_progress_matches_desktop() {
    let (vectors, cases) = recurrence_section("progress");
    let mut failures = Vec::new();
    for case in &cases {
        let actual = repeat_progress(&config(&vectors, case)).map_or(
            Json::Null,
            |RepeatProgress {
                 current,
                 total,
                 percentage,
             }| json!({"current": current, "total": total, "percentage": percentage}),
        );
        if actual != case["expected"] {
            failures.push(format!("{case} -> actual {actual}"));
        }
    }
    report("recurrence.progress", cases.len(), &failures);
}

#[test]
fn repeat_phrase_first_occurrence_matches_desktop() {
    let vectors = vector_file("task-parsing");
    let cases = vectors["repeatPhrase"]["firstOccurrence"]
        .as_array()
        .expect("repeatPhrase.firstOccurrence is an array");
    assert!(!cases.is_empty(), "repeatPhrase.firstOccurrence has cases");
    let mut failures = Vec::new();
    for case in cases {
        let actual =
            json!(first_occurrence_for(&config(&vectors, case), instant(&case["from"])).key());
        if actual != case["expected"] {
            failures.push(format!("{case} -> actual {actual}"));
        }
    }
    report("repeatPhrase.firstOccurrence", cases.len(), &failures);
}
