//! Enrichment writes (spec 006 IB022, D3, D4): link previews and voice
//! transcripts written back onto a capture, never replacing a richer value a
//! peer already wrote.

use rusqlite::Connection;
use serde_json::{Map, Value};

use crate::api::errors::StorageError;
use crate::storage::repositories::Change;
use crate::sync::outbox::Durable;

use super::write::{edit, require_live};
use super::{InboxItem, urls};

/// Merges keys into `metadata` without dropping ones a peer wrote.
///
/// D3: a richer value is never replaced by a poorer one — a key already
/// holding a non-empty value keeps it unless `overwrite` is set, and
/// `fetchStatus` only moves forward (`pending` → `failed` → `complete`).
pub fn merge_metadata(
    conn: &Connection,
    item_id: &str,
    patch: &Map<String, Value>,
    processing_status: Option<&str>,
    overwrite: bool,
    device_id: &str,
    now_ms: i64,
) -> Result<Durable<InboxItem>, StorageError> {
    let item = require_live(conn, item_id)?;
    let mut merged = match item.metadata {
        Some(Value::Object(map)) => map,
        _ => Map::new(),
    };
    for (key, value) in patch {
        let empty = |v: &Value| v.is_null() || v.as_str().is_some_and(str::is_empty);
        let keep = !overwrite
            && merged.get(key).is_some_and(|existing| !empty(existing))
            && (key != "fetchStatus"
                || merged.get(key).and_then(Value::as_str) == Some("complete"));
        if !keep && !(empty(value) && merged.contains_key(key)) {
            merged.insert(key.clone(), value.clone());
        }
    }
    let mut changes = vec![("metadata", Change::Set(Value::Object(merged)))];
    if let Some(status) = processing_status {
        changes.push(("processingStatus", Change::set(status)));
    }
    edit(conn, item_id, changes, device_id, now_ms)
}

/// Writes the enrichment result for a link: title (only when the stored one is
/// still the URL-derived default), description as content, metadata merged.
pub fn complete_link(
    conn: &Connection,
    item_id: &str,
    title: Option<&str>,
    description: Option<&str>,
    patch: &Map<String, Value>,
    device_id: &str,
    now_ms: i64,
) -> Result<Durable<InboxItem>, StorageError> {
    let item = require_live(conn, item_id)?;
    let default_title = item.source_url.as_deref().map(urls::title_from_url);
    let mut changes: Vec<(&'static str, Change)> = Vec::new();
    if let Some(title) = title.filter(|t| !t.trim().is_empty())
        && default_title.as_deref() == Some(item.title.as_str())
    {
        changes.push(("title", Change::set(title)));
    }
    if let Some(description) = description.filter(|d| !d.is_empty())
        && item.content.as_deref().is_none_or(str::is_empty)
    {
        changes.push(("content", Change::set(description)));
    }
    let mut metadata = match item.metadata {
        Some(Value::Object(map)) => map,
        _ => Map::new(),
    };
    for (key, value) in patch {
        let richer = metadata
            .get(key)
            .is_none_or(|v| v.is_null() || v.as_str() == Some(""));
        if richer || key == "fetchStatus" {
            metadata.insert(key.clone(), value.clone());
        }
    }
    let status = patch.get("fetchStatus").and_then(Value::as_str) == Some("failed");
    changes.push(("metadata", Change::Set(Value::Object(metadata))));
    changes.push((
        "processingStatus",
        Change::set(if status { "failed" } else { "complete" }),
    ));
    edit(conn, item_id, changes, device_id, now_ms)
}

/// A voice memo's transcript and status (`pending`, `complete`, `failed`).
/// The first sentence becomes the title while it is still the default one.
pub fn set_transcription(
    conn: &Connection,
    item_id: &str,
    transcription: Option<&str>,
    status: &str,
    device_id: &str,
    now_ms: i64,
) -> Result<Durable<InboxItem>, StorageError> {
    let item = require_live(conn, item_id)?;
    let mut changes = vec![
        ("transcriptionStatus", Change::set(status)),
        (
            "transcription",
            Change::Set(transcription.map_or(Value::Null, Value::from)),
        ),
    ];
    if let Some(title) = transcription.and_then(title_from_transcription)
        && is_default_voice_title(&item.title)
    {
        changes.push(("title", Change::set(title)));
    }
    edit(conn, item_id, changes, device_id, now_ms)
}

/// `isAutoGeneratedVoiceMemoTitle`.
fn is_default_voice_title(title: &str) -> bool {
    title == "Voice memo"
        || title
            .strip_prefix("Voice memo (")
            .and_then(|rest| rest.strip_suffix(')'))
            .and_then(|mmss| mmss.split_once(':'))
            .is_some_and(|(m, s)| {
                !m.is_empty()
                    && m.chars().all(|c| c.is_ascii_digit())
                    && s.len() == 2
                    && s.chars().all(|c| c.is_ascii_digit())
            })
}

/// `titleFromTranscription`: the first sentence, 60 characters at most.
fn title_from_transcription(text: &str) -> Option<String> {
    let trimmed = text.trim();
    if trimmed.is_empty() {
        return None;
    }
    let end = trimmed
        .find(['.', '!', '?'])
        .map_or(trimmed.len(), |i| i + 1);
    let sentence = trimmed[..end].trim();
    if sentence.is_empty() {
        return None;
    }
    let chars: Vec<char> = sentence.chars().collect();
    Some(if chars.len() > 60 {
        format!("{}...", chars[..57].iter().collect::<String>().trim())
    } else {
        sentence.to_owned()
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_voice_titles_give_way_to_the_first_sentence() {
        assert!(is_default_voice_title("Voice memo (0:42)"));
        assert!(!is_default_voice_title("Dentist"));
        assert_eq!(
            title_from_transcription("Pick up the cable. Then the dentist.").as_deref(),
            Some("Pick up the cable.")
        );
    }
}
