import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import {
  hasObsidianTaskFields,
  obsidianTaskImportBlocker,
  parseObsidianTaskFields,
  parseObsidianTaskLine,
  type ObsidianTaskFields,
  type ObsidianTaskLine
} from './obsidian-tasks'

// Variant Selector 16 is invisible in an editor, so any test that depends on
// its presence asserts on this first: an editor or a lint autofix that strips
// the character has to fail loudly instead of silently weakening the test.
function hasVariantSelector16(text: string): boolean {
  return /\uFE0F/u.test(text)
}

const EMPTY_FIELDS: ObsidianTaskFields = {
  description: '',
  tags: [],
  priority: null,
  dueDate: null,
  scheduledDate: null,
  startDate: null,
  createdDate: null,
  doneDate: null,
  cancelledDate: null,
  recurrenceText: null,
  recurrence: null,
  onCompletion: null,
  id: null,
  dependsOn: [],
  blockLink: null
}

function fields(overrides: Partial<ObsidianTaskFields> = {}): ObsidianTaskFields {
  return { ...EMPTY_FIELDS, ...overrides }
}

function taskLine(
  description: string,
  overrides: Partial<ObsidianTaskLine> = {}
): ObsidianTaskLine {
  return {
    ...EMPTY_FIELDS,
    description,
    indentation: '',
    listMarker: '-',
    statusChar: ' ',
    statusType: 'TODO',
    ...overrides
  }
}

function readFixture(name: string): string[] {
  const raw = readFileSync(
    new URL(`./obsidian-tasks-fixtures/${name}.approved.md`, import.meta.url),
    'utf8'
  )
  return raw
    .split('\n')
    .map((line) => line.replace(/\r$/, ''))
    .filter((line) => line.trim().length > 0 && !line.trimStart().startsWith('<!--'))
}

// Every fixture line begins with the plugin's own `#task` global filter tag.
function taskTagged(
  description: string,
  overrides: Partial<ObsidianTaskLine> = {}
): ObsidianTaskLine {
  return taskLine(description, { tags: ['#task'], ...overrides })
}

const FIXTURE_PAIRS: { name: string; expected: ObsidianTaskLine[] }[] = [
  {
    name: 'Dates',
    expected: [
      taskTagged('#task Has a created date', { createdDate: '2023-04-13' }),
      taskTagged('#task Has a scheduled date', { scheduledDate: '2023-04-14' }),
      taskTagged('#task Has a start date', { startDate: '2023-04-15' }),
      taskTagged('#task Has a due date', { dueDate: '2023-04-16' }),
      taskTagged('#task Has a done date', {
        doneDate: '2023-04-17',
        statusChar: 'x',
        statusType: 'DONE'
      }),
      taskTagged('#task Has a cancelled date', {
        cancelledDate: '2023-04-18',
        statusChar: '-',
        statusType: 'CANCELLED'
      })
    ]
  },
  {
    name: 'Dependencies',
    expected: [
      taskTagged('#task do this first', { id: 'dcf64c' }),
      taskTagged('#task do this after first and some other task', {
        dependsOn: ['dcf64c', '0h17ye']
      })
    ]
  },
  {
    name: 'OnCompletion',
    expected: [
      taskTagged('#task Keep this task when done'),
      taskTagged('#task Keep this task when done too', { onCompletion: 'keep' }),
      taskTagged('#task Remove this task when done', { onCompletion: 'delete' }),
      taskTagged('#task Remove completed instance of this recurring task when done', {
        recurrenceText: 'every day',
        recurrence: { frequency: 'daily', interval: 1, fromCompletion: false },
        onCompletion: 'delete'
      })
    ]
  },
  {
    name: 'Priorities',
    expected: [
      taskTagged('#task Lowest priority', { priority: 'lowest' }),
      taskTagged('#task Low priority', { priority: 'low' }),
      taskTagged('#task Normal priority'),
      taskTagged('#task Medium priority', { priority: 'medium' }),
      taskTagged('#task High priority', { priority: 'high' }),
      taskTagged('#task Highest priority', { priority: 'highest' })
    ]
  }
]

describe('fixtures generated by the Obsidian Tasks plugin', () => {
  for (const { name, expected } of FIXTURE_PAIRS) {
    for (const format of ['tasksPluginEmoji', 'dataview'] as const) {
      describe(`${name}_${format}`, () => {
        const lines = readFixture(`${name}_${format}`)

        it('has the expected number of lines', () => {
          expect(lines).toHaveLength(expected.length)
        })

        it.each(expected.map((value, index) => [index, value] as const))(
          'parses line %i',
          (index, want) => {
            expect(parseObsidianTaskLine(lines[index])).toEqual(want)
          }
        )
      })
    }

    it(`${name}: both formats produce identical fields`, () => {
      const emoji = readFixture(`${name}_tasksPluginEmoji`).map(parseObsidianTaskLine)
      const dataview = readFixture(`${name}_dataview`).map(parseObsidianTaskLine)
      expect(emoji).toEqual(dataview)
      expect(emoji).toEqual(expected)
    })
  }
})

describe('Variant Selector 16', () => {
  it('parses a high priority with a trailing Variant Selector 16', () => {
    const line = '⏫️'
    expect(hasVariantSelector16(line)).toBe(true)
    expect(parseObsidianTaskFields(line)).toEqual(fields({ priority: 'high' }))
  })

  it('parses a high priority without a Variant Selector 16', () => {
    const line = '⏫'
    expect(hasVariantSelector16(line)).toBe(false)
    expect(parseObsidianTaskFields(line)).toEqual(fields({ priority: 'high' }))
  })

  it('parses a scheduled date with a Variant Selector 16', () => {
    const input = '⏳️ 2024-11-18'
    expect(hasVariantSelector16(input)).toBe(true)
    expect(parseObsidianTaskFields(input)).toEqual(fields({ scheduledDate: '2024-11-18' }))
  })

  it('parses dependsOn with a Variant Selector 16', () => {
    const input = '⛔️ F12345'
    expect(hasVariantSelector16(input)).toBe(true)
    expect(parseObsidianTaskFields(input)).toEqual(fields({ dependsOn: ['F12345'] }))
  })

  it('parses dependsOn without a Variant Selector 16', () => {
    const input = '⛔ F12345'
    expect(hasVariantSelector16(input)).toBe(false)
    expect(parseObsidianTaskFields(input)).toEqual(fields({ dependsOn: ['F12345'] }))
  })
})

describe('alternate emoji symbols', () => {
  it.each(['📅', '📆', '🗓'])('parses a due date written as %s', (symbol) => {
    expect(parseObsidianTaskFields(`${symbol} 2021-06-20`)).toEqual(
      fields({ dueDate: '2021-06-20' })
    )
  })

  it.each(['⏳', '⌛'])('parses a scheduled date written as %s', (symbol) => {
    expect(parseObsidianTaskFields(`${symbol} 2021-06-20`)).toEqual(
      fields({ scheduledDate: '2021-06-20' })
    )
  })
})

describe('status characters', () => {
  it.each([
    [' ', 'TODO'],
    ['x', 'DONE'],
    ['X', 'DONE'],
    ['/', 'IN_PROGRESS'],
    ['-', 'CANCELLED'],
    ['?', 'TODO'],
    ['b', 'TODO']
  ] as const)('maps [%s] to %s', (statusChar, statusType) => {
    const parsed = parseObsidianTaskLine(`- [${statusChar}] Buy milk`)
    expect(parsed?.statusChar).toBe(statusChar)
    expect(parsed?.statusType).toBe(statusType)
  })
})

describe('block links', () => {
  it('peels a trailing block link off the description', () => {
    expect(parseObsidianTaskFields('Buy milk 📅 2026-01-01 ^abc123')).toEqual(
      fields({ description: 'Buy milk', dueDate: '2026-01-01', blockLink: '^abc123' })
    )
  })

  it('keeps a caret that is not a block link in the description', () => {
    expect(parseObsidianTaskFields('Buy milk ^not a block link')).toEqual(
      fields({ description: 'Buy milk ^not a block link' })
    )
  })

  it('exposes the block link from a whole line', () => {
    expect(parseObsidianTaskLine('- [ ] Buy milk ^abc-123')).toEqual(
      taskLine('Buy milk', { blockLink: '^abc-123' })
    )
  })
})

describe('mixed emoji and dataview fields', () => {
  // Verbatim from the plugin's own DataviewTaskSerializer test suite.
  const line =
    'Wobble [priority::high] #tag1 [completion:: 2024-09-04] #tag2  [due::2025-10-05] #tag3 [scheduled::2022-07-02] #tag4 [start::2023-08-03] #tag5  [repeat::every day]  #tag6 #tag7 #tag8 #tag9 #tag10'

  it('strips every field and re-appends the trailing tags in order', () => {
    expect(parseObsidianTaskFields(line)).toEqual(
      fields({
        description: 'Wobble #tag1 #tag2 #tag3 #tag4 #tag5 #tag6 #tag7 #tag8 #tag9 #tag10',
        tags: [
          '#tag1',
          '#tag2',
          '#tag3',
          '#tag4',
          '#tag5',
          '#tag6',
          '#tag7',
          '#tag8',
          '#tag9',
          '#tag10'
        ],
        priority: 'high',
        doneDate: '2024-09-04',
        dueDate: '2025-10-05',
        scheduledDate: '2022-07-02',
        startDate: '2023-08-03',
        recurrenceText: 'every day',
        recurrence: { frequency: 'daily', interval: 1, fromCompletion: false }
      })
    )
  })
})

describe('dataview inline field syntax', () => {
  it.each(['[due::2021-06-20]', '[due:: 2021-06-20]', '[ due::2021-06-20 ]', '(due:: 2021-06-20)'])(
    'tolerates whitespace and brackets in %s',
    (input) => {
      expect(parseObsidianTaskFields(input)).toEqual(fields({ dueDate: '2021-06-20' }))
    }
  )

  it('is case sensitive', () => {
    expect(parseObsidianTaskFields('[dependson:: F12345]')).toEqual(
      fields({ description: '[dependson:: F12345]' })
    )
  })

  it('parses a dataview id and dependsOn', () => {
    expect(parseObsidianTaskFields('Wobble  [id:: abc123]')).toEqual(
      fields({ description: 'Wobble', id: 'abc123' })
    )
    expect(parseObsidianTaskFields('Wobble  [dependsOn:: abc123,def456]')).toEqual(
      fields({ description: 'Wobble', dependsOn: ['abc123', 'def456'] })
    )
  })
})

describe('dependsOn', () => {
  it('drops the spaces around each id', () => {
    expect(parseObsidianTaskFields('⛔ ab , CD ,  EF  ,    GK')).toEqual(
      fields({ dependsOn: ['ab', 'CD', 'EF', 'GK'] })
    )
  })
})

describe('recurrence', () => {
  it.each([
    ['every day', { frequency: 'daily', interval: 1, fromCompletion: false }],
    ['every 3 days', { frequency: 'daily', interval: 3, fromCompletion: false }],
    ['every week', { frequency: 'weekly', interval: 1, fromCompletion: false }],
    ['every 2 weeks', { frequency: 'weekly', interval: 2, fromCompletion: false }],
    ['every month', { frequency: 'monthly', interval: 1, fromCompletion: false }],
    ['every 6 months', { frequency: 'monthly', interval: 6, fromCompletion: false }],
    ['every year', { frequency: 'yearly', interval: 1, fromCompletion: false }],
    ['every 2 years', { frequency: 'yearly', interval: 2, fromCompletion: false }],
    ['every week when done', { frequency: 'weekly', interval: 1, fromCompletion: true }],
    [
      'every weekday',
      { frequency: 'weekly', interval: 1, daysOfWeek: [1, 2, 3, 4, 5], fromCompletion: false }
    ],
    ['every Monday', { frequency: 'weekly', interval: 1, daysOfWeek: [1], fromCompletion: false }],
    [
      'every Monday, Wednesday',
      { frequency: 'weekly', interval: 1, daysOfWeek: [1, 3], fromCompletion: false }
    ],
    [
      'every Tuesday and Thursday',
      { frequency: 'weekly', interval: 1, daysOfWeek: [2, 4], fromCompletion: false }
    ],
    [
      'every Sun, Sat',
      { frequency: 'weekly', interval: 1, daysOfWeek: [0, 6], fromCompletion: false }
    ],
    [
      'every friday when done',
      { frequency: 'weekly', interval: 1, daysOfWeek: [5], fromCompletion: true }
    ]
  ] as const)('maps %s', (text, recurrence) => {
    const parsed = parseObsidianTaskFields(`Wobble 🔁 ${text}`)
    expect(parsed.recurrenceText).toBe(text)
    expect(parsed.recurrence).toEqual(recurrence)
    expect(parsed.description).toBe('Wobble')
  })

  it('keeps the raw text but gives up on an unsupported rule', () => {
    const parsed = parseObsidianTaskFields('Wobble 🔁 every 3rd Thursday')
    expect(parsed.recurrenceText).toBe('every 3rd Thursday')
    expect(parsed.recurrence).toBeNull()
  })

  it('reads the dataview spelling too', () => {
    const parsed = parseObsidianTaskFields('Wobble  [repeat:: every week when done]')
    expect(parsed.recurrenceText).toBe('every week when done')
    expect(parsed.recurrence).toEqual({
      frequency: 'weekly',
      interval: 1,
      fromCompletion: true
    })
  })
})

describe('tags', () => {
  it('preserves casing and dedupes case-insensitively, keeping the first casing', () => {
    const parsed = parseObsidianTaskFields('#Work note #work #WORK #Home')
    expect(parsed.tags).toEqual(['#Work', '#Home'])
  })

  it('collects tags that were peeled from the end', () => {
    const parsed = parseObsidianTaskFields('Wobble #alpha 📅 2026-01-01 #beta')
    expect(parsed.description).toBe('Wobble #alpha #beta')
    expect(parsed.tags).toEqual(['#alpha', '#beta'])
    expect(parsed.dueDate).toBe('2026-01-01')
  })
})

describe('parseObsidianTaskLine', () => {
  it.each(['', 'Just a paragraph', '- a bare list item', '  not a task at all', '[ ] no marker'])(
    'returns null for %s',
    (line) => {
      expect(parseObsidianTaskLine(line)).toBeNull()
    }
  )

  it('parses an indented task', () => {
    expect(parseObsidianTaskLine('    - [ ] Buy milk 📅 2026-01-01')).toEqual(
      taskLine('Buy milk', { indentation: '    ', dueDate: '2026-01-01' })
    )
  })

  it('parses a blockquoted task', () => {
    expect(parseObsidianTaskLine('> - [x] Buy milk')).toEqual(
      taskLine('Buy milk', { indentation: '> ', statusChar: 'x', statusType: 'DONE' })
    )
  })

  it('parses a numbered list task', () => {
    expect(parseObsidianTaskLine('1. [ ] Buy milk')).toEqual(
      taskLine('Buy milk', { listMarker: '1.' })
    )
  })
})

describe('obsidianTaskImportBlocker', () => {
  it.each([
    ['Buy milk ^abc123', 'block-link'],
    ['Buy milk 🆔 dcf64c', 'task-id'],
    ['Buy milk  [id:: dcf64c]', 'task-id'],
    ['Buy milk ⛔ dcf64c', 'depends-on'],
    ['Buy milk  [dependsOn:: dcf64c]', 'depends-on'],
    ['Buy milk 🆔 dcf64c ^abc123', 'block-link'],
    ['Buy milk ⛔ dcf64c 🆔 abc', 'task-id']
  ] as const)('reports %s as %s', (text, blocker) => {
    expect(obsidianTaskImportBlocker(text)).toBe(blocker)
  })

  it.each(['Buy milk', 'Buy milk 📅 2026-01-01 ⏫', 'Buy milk #errand'])('clears %s', (text) => {
    expect(obsidianTaskImportBlocker(text)).toBeNull()
  })
})

describe('vaults that do not use the plugin', () => {
  it('recognises nothing in a plain line', () => {
    expect(hasObsidianTaskFields('Buy milk')).toBe(false)
    expect(parseObsidianTaskFields('Buy milk')).toEqual(fields({ description: 'Buy milk' }))
  })

  it('leaves a plain line untouched through the whole-line parser', () => {
    expect(parseObsidianTaskLine('- [ ] Buy milk')).toEqual(taskLine('Buy milk'))
  })

  it.each([
    'Buy milk 📅 2026-01-01',
    'Buy milk  [due:: 2026-01-01]',
    'Buy milk #errand',
    'Buy milk ^abc123'
  ])('recognises %s', (text) => {
    expect(hasObsidianTaskFields(text)).toBe(true)
  })
})
