appId: com.memrynote.memry
productName: memry
electronUpdaterCompatibility: '>=2.16'
directories:
  buildResources: build
files:
  - '!**/.vscode/*'
  - '!src/*'
  - '!config/*'
  - '!electron.vite.config.{js,ts,mjs,cjs}'
  - '!{.eslintcache,eslint.config.mjs,.prettierignore,.prettierrc.yaml,CHANGELOG.md,README.md}'
  - '!{.env,.env.*,.npmrc,pnpm-lock.yaml}'
  - '!{tsconfig.json,tsconfig.node.json,tsconfig.web.json}'
asarUnpack:
  - resources/**
win:
  executableName: memry
nsis:
  artifactName: memry-${version}-setup.${ext}
  shortcutName: ${productName}
  uninstallDisplayName: ${productName}
  createDesktopShortcut: always
mac:
  artifactName: memry-${version}-${arch}.${ext}
  entitlementsInherit: build/entitlements.mac.plist
  extendInfo:
    - NSCameraUsageDescription: Application requests access to the device's camera.
    - NSMicrophoneUsageDescription: Application requests access to the device's microphone.
    - NSDocumentsFolderUsageDescription: Application requests access to the user's Documents folder.
    - NSDownloadsFolderUsageDescription: Application requests access to the user's Downloads folder.
  notarize: true
linux:
  target:
    - AppImage
    - deb
  maintainer: electronjs.org
  category: Utility
appImage:
  artifactName: memry-${version}.${ext}
npmRebuild: false
publish:
  provider: github
  owner: memrynote
  repo: memry
  releaseType: release
  tagNamePrefix: ''
electronDownload:
  mirror: https://npmmirror.com/mirrors/electron/
