extends: file:config/electron-builder.yml
beforeBuild: ./scripts/before-build-external-node-modules.cjs
npmRebuild: true
dmg:
  size: 3g
extraResources:
  - from: node_modules
    to: node_modules
    filter:
      - '**/*'
      - '.pnpm'
      - '.pnpm/**/*'
      - '.modules.yaml'
      - '!**/*.map'
      - '!**/*.a'
      - '!**/*.o'
      - '!**/{coverage,doc,docs,example,examples,test,tests,__tests__}/**'
      - '!**/re2/vendor/**'
      - '!**/build/Release/obj.target/**'
      - '!electron'
      - '!electron/**/*'
      - '!**/node_modules/electron'
      - '!**/node_modules/electron/**/*'
